import type { Role } from "@/lib/roles";

/**
 * The App guide (/guide): every function of LeMoSp, where to find it and how to use it, step by step.
 * English text is the key; the page translates it with tr() (Kiswahili in src/lib/sw.ts).
 *
 * `phone`: the path on a phone, starting from the bottom bar ("More" opens the menu).
 * `laptop`: the path in the side menu on a laptop or tablet.
 * `roles`: who can use it ("all": everyone in the company; "managers": the Management role).
 * `feature`: hidden from the menus when the company has that feature switched off (Settings → Features).
 * When you add a screen to the app, add it here too.
 */

export type GuideTopic = {
  id: string;
  title: string;
  summary: string;
  phone: string[];
  laptop: string[];
  href?: string;
  roles: Role[] | "all" | "managers";
  feature?: string;
  steps: string[];
  tips?: string[];
};

export type GuideSection = { id: string; title: string; intro: string; topics: GuideTopic[] };

const SALES: Role[] = ["management", "sales", "procurement", "finance"];
const PURCHASING: Role[] = ["management", "procurement", "finance", "warehouse"];
const STOCK: Role[] = ["management", "sales", "procurement", "warehouse", "finance"];
const FINANCE: Role[] = ["management", "finance"];
const NOT_DRIVER: Role[] = ["management", "sales", "procurement", "warehouse", "finance"];

export const GUIDE: GuideSection[] = [
  {
    id: "start",
    title: "Getting started",
    intro: "Signing in, finding your way around and staying informed.",
    topics: [
      {
        id: "find-your-way",
        title: "Finding your way around",
        summary: "How the screens are arranged on a phone and on a laptop.",
        phone: ["Bottom bar"],
        laptop: ["Side menu"],
        roles: "all",
        steps: [
          "On a phone, the bar at the bottom has your most-used screens. Tap More to open the full menu, grouped into Sales, Purchasing, Stock & delivery, Finance, Reports, Add new and Company & account.",
          "On a laptop or tablet, the side menu on the left lists every section you can open.",
          "Tap the company logo at the top left to see the company's details, the team, your account, the language and dark mode, and to sign out.",
          "The search box at the top finds clients, products, quotations and invoices by name or number.",
          "Every list has a search box and a filter. Tap a line to open it; the ← link at the top takes you back.",
        ],
        tips: ["What you see depends on your role and on the features your company has switched on."],
      },
      {
        id: "sign-in",
        title: "Signing in and two-step verification",
        summary: "Your password, and an optional 6-digit code from an authenticator app for extra safety.",
        phone: ["Sign-in page"],
        laptop: ["Sign-in page"],
        href: "/account",
        roles: "all",
        steps: [
          "Open the app and sign in with your email and password. Forgot your password? Tap Forgot your password? and follow the email.",
          "To turn on two-step verification, open Your account → Security and follow the steps with an authenticator app such as Google Authenticator.",
          "From then on, after your password the app asks for the 6-digit code from that app.",
        ],
        tips: ["Managers can require two-step verification for the whole company in Settings → Security."],
      },
      {
        id: "install",
        title: "Installing the app on your phone",
        summary: "Put LeMoSp on your home screen so it opens like a normal app.",
        phone: ["Install card on Home"],
        laptop: ["Browser address bar → Install"],
        roles: "all",
        steps: [
          "Android (Chrome): tap Install app on the card that appears, or Chrome menu ⋮ → Install app.",
          "iPhone (Safari): tap Share, then Add to Home Screen.",
          "Open LeMoSp from its icon from then on. When a new version is ready, a message asks you to update.",
        ],
      },
      {
        id: "home",
        title: "Home: the control tower",
        summary: "What needs your attention today, and the key figures, in one place.",
        phone: ["Home screen"],
        laptop: ["Home screen"],
        href: "/",
        roles: "all",
        steps: [
          "Critical items come first (for example overdue invoices or approvals waiting), then items that need attention, then work in progress.",
          "Tap any line to open the list behind it.",
          "Managers see a Statistics row: swipe left and right for key figures, sales and profit by month, money owed by age, sales by industry and top clients.",
        ],
      },
      {
        id: "notifications",
        title: "Notifications",
        summary: "Alerts about approvals, due dates, low stock, payments and more, in the app, on your phone and by email.",
        phone: ["Bell at the top right"],
        laptop: ["Bell at the top right"],
        href: "/notifications",
        roles: "all",
        steps: [
          "Tap the bell to see your alerts; the number shows how many are unread.",
          "Turn on phone notifications on the Notifications page so alerts arrive even when the app is closed.",
          "Choose which alerts you also want by email.",
        ],
      },
      {
        id: "language",
        title: "Language and appearance",
        summary: "English or Kiswahili, light or dark.",
        phone: ["EN·SW button at the top"],
        laptop: ["EN·SW button at the top"],
        roles: "all",
        steps: [
          "Tap EN·SW at the top to switch between English and Kiswahili.",
          "Choose light, dark or automatic in Your account → Appearance (also in the company panel).",
        ],
      },
      {
        id: "app-lock",
        title: "App lock",
        summary: "When you come back to the app, it asks for your password before showing anything.",
        phone: ["More", "Company & account", "Your account"],
        laptop: ["More", "Your account"],
        href: "/account",
        roles: "all",
        steps: [
          "The lock screen appears when you reopen the app or switch back to it from another app.",
          "Enter your password (and code, if two-step is on) to continue where you left off.",
          "Choose when it asks in Your account → Security: every time, after 1, 5 or 15 minutes away, or never.",
        ],
        tips: ["The driver screen is not locked, so drivers can record deliveries quickly."],
      },
    ],
  },
  {
    id: "records",
    title: "Clients, suppliers and products",
    intro: "The records everything else is built on.",
    topics: [
      {
        id: "clients",
        title: "Clients",
        summary: "Companies you sell to: contacts, TIN/VRN, delivery sites, payment terms and credit limits.",
        phone: ["More", "Sales", "Clients"],
        laptop: ["Clients"],
        href: "/clients",
        roles: "all",
        feature: "customers",
        steps: [
          "Tap + New client and fill in the company, industry, TIN/VRN, address, delivery sites and payment terms.",
          "Open a client to add contacts, see their quotations, invoices and account balance, and open their statement.",
          "Management and finance can set a credit limit. Invoices that go above it need a manager to issue them.",
          "Archive a client you no longer work with; their history is kept.",
        ],
      },
      {
        id: "suppliers",
        title: "Suppliers",
        summary: "Companies you buy from: country, currency, lead time, payment terms and Incoterms.",
        phone: ["More", "Purchasing", "Suppliers"],
        laptop: ["Purchasing", "Suppliers"],
        href: "/suppliers",
        roles: ["management", "procurement", "finance", "warehouse"],
        feature: "suppliers",
        steps: [
          "Tap + New supplier and fill in the contact, country, currency, lead time and terms.",
          "Open a supplier to see their purchase orders, bills and statement.",
        ],
      },
      {
        id: "products",
        title: "Products (catalogue)",
        summary: "Everything you sell: SKU, brand, part number, unit, price, reorder level and safety details.",
        phone: ["More", "Stock & delivery", "Products"],
        laptop: ["Products"],
        href: "/products",
        roles: "all",
        feature: "products",
        steps: [
          "Tap + New product and enter the name, SKU, category, brand, unit and selling price.",
          "Set a reorder level so the app warns you when stock runs low.",
          "For chemicals and lubricants, record hazard details and whether the safety data sheet (SDS) is on file.",
          "Open a product to see its stock, costs and price history.",
        ],
      },
      {
        id: "import",
        title: "Import from a spreadsheet",
        summary: "Load many clients, suppliers or products at once from Excel.",
        phone: ["More", "Add new", "Import from spreadsheet"],
        laptop: ["More", "Import from spreadsheet"],
        href: "/import",
        roles: "managers",
        steps: [
          "Download the template, fill it in Excel and save it.",
          "Upload the file. The app checks every row and shows what will be added and any problems.",
          "Confirm to load the records.",
        ],
      },
    ],
  },
  {
    id: "sales",
    title: "Sales",
    intro: "From a client's request to a won order.",
    topics: [
      {
        id: "client-rfqs",
        title: "Client RFQs (requests for quotation)",
        summary: "Record every request for prices, however it arrives: email, phone, WhatsApp, visit or tender.",
        phone: ["More", "Sales", "Client RFQs"],
        laptop: ["Sales", "Client RFQs"],
        href: "/rfqs",
        roles: SALES,
        feature: "client_rfqs",
        steps: [
          "Tap + New client RFQ, choose the client, how it arrived and the due date.",
          "Add the items the client asked for.",
          "Need supplier prices first? Press Request supplier quotes.",
          "When ready, press Create quotation from these items. You get a reminder when the RFQ is due.",
        ],
      },
      {
        id: "quotations",
        title: "Quotations",
        summary: "Prices for a client, with approval rules, a branded PDF and the client's answer.",
        phone: ["More", "Sales", "Quotations"],
        laptop: ["Sales", "Quotations"],
        href: "/quotations",
        roles: SALES,
        feature: "quotations",
        steps: [
          "Create a quotation from an RFQ or with + New quotation. Add items from the catalogue, set prices, discounts, delivery time and payment terms.",
          "Press Submit quotation. Large quotations, low margins or big discounts go to management for approval; others are approved straight away.",
          "Press Preview PDF or Open PDF and share it by WhatsApp or email, then press I have sent it to the client.",
          "When the client answers, press Client accepted (add their PO number) or Client rejected.",
          "Need to change a sent quotation? Press Make a revision; the old one is kept.",
          "From an accepted quotation: Create purchase order, Request supplier quotes or Create delivery note.",
        ],
        tips: ["Management, procurement and finance see the cost, margin and profit of each quotation."],
      },
      {
        id: "follow-ups",
        title: "Quotation follow-ups",
        summary: "Reminders to follow up sent quotations, with a ready-made message.",
        phone: ["More", "Sales", "Quotations", "open a quotation"],
        laptop: ["Sales", "Quotations", "open a quotation"],
        roles: SALES,
        steps: [
          "After the number of days set by your managers, the bell reminds you to follow up a sent quotation.",
          "On the quotation, the Follow up card has a ready-made WhatsApp, SMS or email message in English or Kiswahili.",
          "Press + Log a follow-up to note what was said and when to follow up again.",
        ],
        tips: ["Managers set the number of days in Settings → Company details → Follow-ups and reminders."],
      },
      {
        id: "sales-overview",
        title: "Sales overview",
        summary: "Open RFQs, quotations waiting for approval and quotations waiting for the client's answer.",
        phone: ["Sales (bottom bar)"],
        laptop: ["Sales"],
        href: "/sales",
        roles: SALES,
        steps: ["Open Sales to see what is due, what is waiting for approval and what is waiting for clients.", "Tap any line to open it."],
      },
    ],
  },
  {
    id: "purchasing",
    title: "Purchasing",
    intro: "Getting the best price from suppliers and making sure the goods arrive.",
    topics: [
      {
        id: "supplier-rfqs",
        title: "Supplier RFQs and price comparison",
        summary: "Ask several suppliers for prices, enter their replies and compare them side by side.",
        phone: ["More", "Purchasing", "Supplier RFQs"],
        laptop: ["Purchasing", "Supplier RFQs"],
        href: "/supplier-rfqs",
        roles: PURCHASING,
        feature: "supplier_rfqs",
        steps: [
          "Create a supplier RFQ from a client RFQ, a quotation, or + New.",
          "Add the suppliers you want prices from, and share the RFQ PDF with each.",
          "When a supplier replies, enter their prices, lead time and terms.",
          "Press Compare prices to see the best offer per item, then Award & create PO.",
        ],
      },
      {
        id: "purchase-orders",
        title: "Purchase orders",
        summary: "Orders to suppliers, with approvals, a PDF and the supplier's confirmation.",
        phone: ["More", "Purchasing", "Purchase orders"],
        laptop: ["Purchasing", "Purchase orders"],
        href: "/purchase-orders",
        roles: PURCHASING,
        feature: "purchases",
        steps: [
          "Create a PO from an accepted quotation, a supplier RFQ, or + New purchase order.",
          "Check the items, prices, delivery place and terms, then press Submit purchase order. Large POs wait for management approval.",
          "Share the PDF with the supplier and press I have sent it to the supplier, then record their confirmation.",
          "When the supplier's invoice arrives, press Record supplier's invoice.",
        ],
      },
      {
        id: "landed-cost",
        title: "Import costs and landed cost",
        summary: "Add duty, clearing, port, insurance and freight to an order so your margins are real.",
        phone: ["More", "Purchasing", "Purchase orders", "open a PO"],
        laptop: ["Purchasing", "Purchase orders", "open a PO"],
        roles: ["management", "procurement", "finance"],
        steps: [
          "Open the purchase order and go to Import costs & landed cost.",
          "Add each cost with its type, amount and currency.",
          "The costs are shared over the items by value, giving the landed cost per unit, which becomes the product cost.",
        ],
      },
      {
        id: "receive",
        title: "Receiving goods (GRN)",
        summary: "Record what arrived from a supplier, into which store, with batch numbers and expiry dates.",
        phone: ["More", "Purchasing", "Receive goods"],
        laptop: ["Purchasing", "Receive goods"],
        href: "/receiving",
        roles: ["management", "warehouse", "procurement"],
        feature: "goods_received",
        steps: [
          "Open Receive goods: it lists purchase orders waiting for delivery.",
          "Choose the PO, the store and the supplier's delivery note number.",
          "Enter the quantity received for each item, with batch and expiry where needed. Partial deliveries are fine.",
          "Save. Stock goes up and a goods received note (GRN) is created.",
        ],
      },
    ],
  },
  {
    id: "stock",
    title: "Stock and deliveries",
    intro: "Knowing what you have, and getting it to the client.",
    topics: [
      {
        id: "stock",
        title: "Stock on hand",
        summary: "Quantities per store, batches, expiry dates and reorder warnings.",
        phone: ["Stock (bottom bar)", "or More", "Stock & delivery", "Stock"],
        laptop: ["Stock"],
        href: "/stock",
        roles: STOCK,
        feature: "inventory",
        steps: [
          "Each store is a card: tap it to open its items.",
          "The gauge on each item shows its stock against the reorder level: red means reorder now, amber is getting low, green is fine.",
          "Expiring soon and Reorder at the top list what needs action.",
        ],
      },
      {
        id: "adjust",
        title: "Stock adjustments and opening stock",
        summary: "Correct stock after a count, or load your starting stock.",
        phone: ["More", "Stock & delivery", "Stock"],
        laptop: ["Stock"],
        href: "/stock/adjust",
        roles: ["management", "warehouse"],
        steps: [
          "On Stock, press Adjust stock, choose the product, store and the new count, and give a reason.",
          "To start using the app, press Load opening stock and upload your stock list from Excel.",
        ],
      },
      {
        id: "stores",
        title: "Stores (warehouses)",
        summary: "The places where you keep stock.",
        phone: ["More", "Stock & delivery", "Stores"],
        laptop: ["More", "Stores"],
        href: "/warehouses",
        roles: "managers",
        feature: "multi_warehouse",
        steps: ["Add each store with a short code and its address.", "Archive a store you no longer use."],
      },
      {
        id: "deliveries",
        title: "Delivery notes",
        summary: "Send goods to a client: store, site, driver, vehicle and a printed delivery note.",
        phone: ["More", "Stock & delivery", "Deliveries"],
        laptop: ["Deliveries"],
        href: "/deliveries",
        roles: ["management", "sales", "warehouse", "finance"],
        feature: "deliveries",
        steps: [
          "From an accepted quotation press Create delivery note (or + New on Deliveries).",
          "Choose the store, delivery site, contact, driver and vehicle, and check the quantities.",
          "Press Dispatch now. Stock goes out, oldest expiry first, and the driver sees the delivery.",
          "Open PDF prints the delivery note for the truck.",
          "When it is delivered, press Create invoice.",
        ],
      },
      {
        id: "driver",
        title: "Driver app and proof of delivery",
        summary: "Drivers record the receiver's name, signature, a photo and the location, even without signal.",
        phone: ["Deliveries (bottom bar)"],
        laptop: ["Deliveries (side menu)"],
        href: "/driver",
        roles: ["driver", "management", "warehouse"],
        feature: "driver_app",
        steps: [
          "Before leaving, open Deliveries while you have signal so the list is saved on the phone.",
          "At the site, press Record delivery: type the receiver's name, let them sign on the screen and take a photo.",
          "Press Confirm delivery. With no signal it is saved on the phone and sent automatically later.",
          "If you could not deliver, press Record failed delivery and say why. The goods go back into stock.",
        ],
      },
    ],
  },
  {
    id: "finance",
    title: "Finance",
    intro: "Invoices, money in and out, expenses and profit.",
    topics: [
      {
        id: "invoices",
        title: "Invoices",
        summary: "Bill clients, with VAT, payment terms, your bank and mobile-money details on the PDF.",
        phone: ["More", "Finance", "Invoices"],
        laptop: ["Finance", "Invoices"],
        href: "/invoices",
        roles: ["management", "finance", "sales"],
        feature: "invoices",
        steps: [
          "Create an invoice from a delivery (Create invoice) or with + New invoice.",
          "Check the items, prices, VAT and the client's PO number.",
          "Press Issue invoice: it gets its number and due date and is locked.",
          "Open PDF to share it with the client.",
        ],
        tips: ["If the invoice takes the client above their credit limit, only management can issue it."],
      },
      {
        id: "payments",
        title: "Payments received and receipts",
        summary: "Record money from clients (bank, cash, mobile money, cheque) and give a receipt.",
        phone: ["More", "Finance", "Invoices", "open an invoice"],
        laptop: ["Finance", "Invoices", "open an invoice"],
        href: "/payments",
        roles: FINANCE,
        feature: "payments",
        steps: [
          "Open the invoice and press + Record a payment received.",
          "Enter the date, amount and method. For mobile money, choose the service (M-Pesa, Mixx, Airtel Money…) and the transaction code.",
          "Save. The invoice shows Part paid or Paid, and Receipt gives a PDF receipt.",
          "Payments received lists every payment; management can void a wrong one.",
        ],
      },
      {
        id: "reminders",
        title: "Money owed and payment reminders",
        summary: "Who owes what and for how long, with ready-made reminder messages.",
        phone: ["More", "Finance", "Money owed to us"],
        laptop: ["Finance", "Money owed to us"],
        href: "/receivables",
        roles: FINANCE,
        feature: "receivables",
        steps: [
          "Money owed to us shows every client by how late they are: current, 1–30, 31–60, 61–90 and over 90 days.",
          "On an invoice, the Remind the client card has a ready-made WhatsApp, SMS or email message.",
          "Press + Log a reminder or promise to pay. If the client promises a date, reminders pause until then.",
        ],
      },
      {
        id: "bills",
        title: "Supplier bills and payments",
        summary: "Suppliers' invoices, what you have paid and what you still owe.",
        phone: ["More", "Finance", "Supplier bills"],
        laptop: ["Finance", "Supplier bills"],
        href: "/bills",
        roles: ["management", "finance", "procurement"],
        feature: "supplier_bills",
        steps: [
          "Record the supplier's invoice from its purchase order (Record supplier's invoice) or with + Bill on Supplier bills.",
          "When you pay, open the bill and press + Record a payment to the supplier.",
          "Money we owe shows what is due to each supplier, and when.",
        ],
      },
      {
        id: "expenses",
        title: "Expenses",
        summary: "Day-to-day spending (fuel, rent, airtime…) with a photo of the receipt.",
        phone: ["More", "Add new", "+ New expense"],
        laptop: ["More", "Expenses"],
        href: "/expenses",
        roles: "all",
        steps: [
          "Tap + New expense, enter the amount, date, category and how it was paid, and take a photo of the receipt.",
          "Everyone sees their own expenses under My expenses.",
          "Management and finance see all expenses, totals by category, and can void a wrong one.",
          "Managers can edit the list of categories.",
        ],
      },
      {
        id: "profit",
        title: "Profit",
        summary: "Gross profit by order, client, industry and salesperson, month by month.",
        phone: ["More", "Finance", "Profit"],
        laptop: ["Finance", "Profit"],
        href: "/profit",
        roles: FINANCE,
        feature: "profit_analysis",
        steps: ["Open Profit and choose the month.", "Tap a client or order to see the details behind the figures."],
      },
      {
        id: "profit-loss",
        title: "Profit & loss",
        summary: "Sales, cost of goods, expenses and net profit for this month, last month and the year so far.",
        phone: ["More", "Finance", "Profit & loss"],
        laptop: ["Finance", "Profit & loss"],
        href: "/profit-loss",
        roles: FINANCE,
        steps: ["Open Profit & loss to see the figures side by side.", "For other periods, use Reports → Profit & loss by month."],
      },
      {
        id: "statements",
        title: "Statements of account",
        summary: "Everything invoiced and paid for a client or supplier, with the running balance, as a PDF.",
        phone: ["More", "Finance", "Statements"],
        laptop: ["Finance", "Statements"],
        href: "/statements",
        roles: FINANCE,
        steps: [
          "Open Statements, choose a client or supplier and the dates, then Open statement.",
          "Press Open PDF to share it. You can also open it from the client's or supplier's page.",
        ],
      },
      {
        id: "reconcile",
        title: "Check payments against your statement",
        summary: "Tick payments in the app against your mobile-money or bank statement.",
        phone: ["More", "Finance", "Check payments"],
        laptop: ["Finance", "Check payments"],
        href: "/reconcile",
        roles: FINANCE,
        steps: [
          "Open Check payments and choose the method, service and dates.",
          "Tick each payment that appears on your statement, or press Paste a statement to match them automatically.",
          "Checked payments can no longer be changed.",
        ],
        tips: ["Managers add the company's pay numbers in Company details; they print on invoices and reminders."],
      },
      {
        id: "rates",
        title: "Exchange rates",
        summary: "USD, EUR and other rates used for documents in foreign currency.",
        phone: ["More", "Finance", "Exchange rates"],
        laptop: ["Finance", "Exchange rates"],
        href: "/rates",
        roles: FINANCE,
        feature: "multi_currency",
        steps: ["Enter today's rate for each currency you use.", "New quotations, orders and invoices in that currency use it automatically."],
      },
    ],
  },
  {
    id: "reports",
    title: "Reports",
    intro: "Figures for any period, to print or download.",
    topics: [
      {
        id: "reports",
        title: "Reports",
        summary: "Sales, purchasing, stock, deliveries, payments, expenses, profit and lists, for any dates.",
        phone: ["More", "Reports"],
        laptop: ["Reports"],
        href: "/reports",
        roles: NOT_DRIVER,
        steps: [
          "Open Reports and choose a report.",
          "Choose the period (today, this month, last quarter…) or Choose dates for your own from and to dates.",
          "Add filters such as client, supplier, store or status. Under Customise, choose the columns and the order.",
          "Press Show report. Tap a column heading to sort by it.",
          "Press Print, PDF or Excel. Press Save to keep this report with its settings for next time.",
        ],
        tips: ["You only see the reports your role allows."],
      },
      {
        id: "export",
        title: "Export all your data",
        summary: "Download everything the company has in the app, as a backup or to move to other software.",
        phone: ["More", "Company & account", "Settings", "Export data"],
        laptop: ["More", "Settings", "Export data"],
        href: "/settings/export",
        roles: "managers",
        feature: "data_export",
        steps: ["Download one table as CSV for Excel, or everything in one file.", "You may be asked for your password again first."],
      },
    ],
  },
  {
    id: "company",
    title: "Company settings (managers)",
    intro: "Setting up the company, the team and security.",
    topics: [
      {
        id: "company-details",
        title: "Company details and branding",
        summary: "Name, TIN, VRN, logo, colours, bank and pay numbers, VAT, approval limits and document terms.",
        phone: ["Tap the company logo", "Company details"],
        laptop: ["More", "Company details & branding"],
        href: "/settings/company",
        roles: "all",
        steps: [
          "Managers fill in the company's legal details, logo and colours; they appear on every PDF.",
          "Set VAT, the approval limits for quotations and purchase orders, the minimum margin and payment days.",
          "Add bank details and mobile-money pay numbers to print on invoices.",
          "Set the follow-up and reminder days.",
        ],
        tips: ["Other roles can view the company's details but not change them."],
      },
      {
        id: "team",
        title: "Team and roles",
        summary: "Invite people and give each one a role: Management, Sales, Procurement, Warehouse, Driver or Finance.",
        phone: ["Tap the company logo", "Team"],
        laptop: ["More", "Team & roles"],
        href: "/settings/team",
        roles: "managers",
        feature: "team",
        steps: [
          "Press Invite someone, enter their email and choose a role. They get an email to join.",
          "Change someone's role at any time.",
          "Switch access off the day someone leaves. Their past work stays on record.",
        ],
      },
      {
        id: "features",
        title: "Business level and features",
        summary: "Small, Medium or Enterprise, and switching single features on or off.",
        phone: ["More", "Company & account", "Features & business level"],
        laptop: ["More", "Features & business level"],
        href: "/settings/features",
        roles: "managers",
        steps: [
          "Choose the level that fits the company now. It only decides which features start switched on; nothing is deleted when you change it.",
          "Switch any single feature on or off, for example multi-currency for a small importer.",
        ],
      },
      {
        id: "growth",
        title: "Growth and recommendations",
        summary: "Suggestions based on how the business is growing, with a short tutorial for each.",
        phone: ["More", "Company & account", "Growth & recommendations"],
        laptop: ["More", "Growth & recommendations"],
        href: "/growth",
        roles: "all",
        steps: ["Read why a feature is suggested.", "Press Switch on, Remind me in 2 weeks or Dismiss."],
      },
      {
        id: "security",
        title: "Security settings",
        summary: "Require two-step verification, automatic sign-out and password rules for everyone.",
        phone: ["More", "Company & account", "Security"],
        laptop: ["More", "Settings", "Security"],
        href: "/settings/security",
        roles: "managers",
        feature: "security_policy",
        steps: [
          "The security check shows green, orange and red items to improve.",
          "Require two-step verification for everyone, and set automatic sign-out after a time without use.",
          "See the team's sign-in history.",
        ],
      },
      {
        id: "activity",
        title: "Activity log",
        summary: "Every change in the app: who did it and when.",
        phone: ["More", "Company & account", "Activity log"],
        laptop: ["More", "Activity log"],
        href: "/activity",
        roles: "managers",
        feature: "activity",
        steps: ["Open the Activity log and search or filter by person, record or date."],
      },
      {
        id: "backups",
        title: "Backups",
        summary: "The company's data is copied automatically every night.",
        phone: ["More", "Company & account", "Backups"],
        laptop: ["More", "Settings", "Backups"],
        href: "/settings/backups",
        roles: "managers",
        steps: ["See when the last backup ran.", "Press Back up now, or Download a copy.", "Restoring is done by LeMo Tech support from a chosen date."],
      },
      {
        id: "alerts-setup",
        title: "Alerts setup and go-live checklist",
        summary: "Connect phone notifications and email sending, and see what is left before going live.",
        phone: ["More", "Company & account", "Alerts setup"],
        laptop: ["More", "Settings", "Alerts setup"],
        href: "/settings/go-live",
        roles: "managers",
        steps: ["Alerts setup shows whether phone notifications and emails are working, with a test button.", "The Go-live checklist shows what is ready and what is left."],
      },
      {
        id: "close-company",
        title: "Closing the company account",
        summary: "Stop using LeMoSp for this company. All its data is deleted after 30 days.",
        phone: ["Tap the company logo", "Company details", "Close company account"],
        laptop: ["More", "Company details & branding", "Close company account"],
        href: "/settings/company/close",
        roles: "managers",
        steps: ["Download a final backup first.", "Type the company name to confirm.", "You have 30 days to change your mind."],
      },
    ],
  },
  {
    id: "account",
    title: "Your account",
    intro: "Your own details, password and devices.",
    topics: [
      {
        id: "my-account",
        title: "Your details and password",
        summary: "Your name, phone, password, appearance and the companies you belong to.",
        phone: ["Tap the company logo", "Your account"],
        laptop: ["More", "Your account"],
        href: "/account",
        roles: "all",
        steps: [
          "Update your name and phone.",
          "Change your password (you may be asked for the current one).",
          "If you work for more than one company, switch between them here.",
          "Sign out, or sign out on all other devices.",
        ],
      },
      {
        id: "delete-account",
        title: "Deleting your account or removing the app",
        summary: "Delete your account (7 days to change your mind), or just remove the app from a phone.",
        phone: ["Tap the company logo", "Your account"],
        laptop: ["More", "Your account"],
        href: "/account",
        roles: "all",
        steps: [
          "Remove LeMoSp from this phone shows how to uninstall and clears the phone. Your account is not deleted.",
          "Delete my account: type your password and DELETE. You lose access at once and can keep the account by signing in within 7 days.",
          "Business records you created stay with the company, shown as Deleted user.",
        ],
      },
    ],
  },
  {
    id: "more-help",
    title: "Ideas and help",
    intro: "Improving the business and learning the app.",
    topics: [
      {
        id: "suggestions",
        title: "Suggestion Box",
        summary: "Anyone can share an idea; managers review it and follow it up.",
        phone: ["More", "Company & account", "Suggestion Box"],
        laptop: ["More", "Suggestion Box"],
        href: "/suggestions",
        roles: "all",
        feature: "suggestions",
        steps: [
          "Press + New suggestion, choose a category and describe the idea.",
          "Managers approve, reject, assign or mark it implemented, and everyone can comment.",
          "Ideas about the app itself go to LeMo Tech anonymously.",
        ],
      },
      {
        id: "help",
        title: "Help, guided tours and the demo",
        summary: "A short guide for your role, tours of the real screens, and a demo company to practise in.",
        phone: ["Tap the company logo", "Help"],
        laptop: ["Help"],
        href: "/help",
        roles: "all",
        steps: [
          "Help has a step-by-step guide for each role and a button to start the guided tour.",
          "The tour highlights each screen and explains what it does.",
          "To practise without touching real data, sign out and choose a Small, Medium or Large demo on the sign-in page.",
        ],
      },
    ],
  },
];
