// Kiswahili for screen text. Keys are the exact English shown in the app.
// Generated for Stage 9; please have a native speaker review.
export const SW: Record<string, string> = {
  "Appearance": "Mwonekano",
  "Auto": "Otomatiki",
  "Light": "Mwanga",
  "Dark": "Giza",
  "Auto follows your phone's light or dark setting.": "Otomatiki hufuata mpangilio wa mwanga au giza wa simu yako.",
  "Close": "Funga",
  " & profit": " na faida",
  " has": " ina",
  " · below 12%, needs approval when quoting": " · chini ya 12%, inahitaji idhini wakati wa kunukuu",
  " · not a catalogue item (no stock kept)": " · si bidhaa ya katalogi (haiwekwi stoku)",
  " · not in catalogue": " · haipo kwenye katalogi",
  " · voided": " · imebatilishwa",
  "% margin": "% faida",
  "(before VAT)": "(kabla ya VAT)",
  "(map)": "(ramani)",
  "(no name)": "(hakuna jina)",
  "(oldest expiry first) and sends the delivery to the driver's phone.": "(inayoisha muda kwanza) na kutuma uwasilishaji kwenye simu ya dereva.",
  "(reorder at": "(agiza tena kwenye",
  "(this one)": "(hii)",
  "). Its items are copied in at the last known cost.": "). Bidhaa zake zinanakiliwa kwa gharama ya mwisho inayojulikana.",
  "). Set the rate under Details first.": "). Weka kiwango kwanza kwenye Maelezo.",
  "+ Add a contact": "+ Ongeza mtu wa mawasiliano",
  "+ Add a cost": "+ Ongeza gharama",
  "+ Add an item": "+ Ongeza bidhaa",
  "+ Ask suppliers": "+ Uliza wasambazaji",
  "+ Bill": "+ Bili",
  "+ Delivery note": "+ Hati ya uwasilishaji",
  "+ Invoice": "+ Ankara",
  "+ New": "+ Mpya",
  "+ New PO": "+ PO mpya",
  "+ New RFQ": "+ RFQ mpya",
  "+ New client": "+ Mteja mpya",
  "+ New product": "+ Bidhaa mpya",
  "+ New quotation": "+ Nukuu ya bei mpya",
  "+ New supplier": "+ Msambazaji mpya",
  "+ Quotation": "+ Nukuu ya bei",
  "+ Record a payment received": "+ Rekodi malipo yaliyopokelewa",
  "+ Record a payment to the supplier": "+ Rekodi malipo kwa msambazaji",
  ", add": ", ongeza",
  ", add and verify your domain (triumphsuppliers.co.tz), create an API key, and add to Netlify:": ", ongeza na uthibitishe kikoa chako (triumphsuppliers.co.tz), unda ufunguo wa API, na uongeze kwenye Netlify:",
  ", open it from there, then come back to this page.": ", ifungue kutoka hapo, kisha urudi kwenye ukurasa huu.",
  ", row": ", safu",
  ", run this once (you can use the random text below, or your own of 24+ characters):": ", endesha hii mara moja (unaweza kutumia maandishi nasibu hapa chini, au yako mwenyewe ya herufi 24+):",
  ". Check the spelling against the Suppliers tab, or set it on each product.": ". Linganisha tahajia na kichupo cha Wasambazaji, au iweke kwenye kila bidhaa.",
  ". Cost of goods uses each product's cost when the invoice was issued (landed cost if it was applied). Freight, duty and clearing on purchase orders are part of the landed cost; transport, bank charges and similar costs are added on the order.": ". Gharama ya bidhaa hutumia gharama ya kila bidhaa wakati ankara ilipotolewa (gharama halisi ya kufikisha kama ilitumika). Usafirishaji, ushuru na uondoshaji kwenye oda za ununuzi ni sehemu ya gharama halisi ya kufikisha; usafiri, ada za benki na gharama nyingine zinaongezwa kwenye oda.",
  ". Generate a pair here (it is not saved anywhere — copy both straight into Netlify, keep the private one secret):": ". Tengeneza jozi hapa (haihifadhiwi popote — nakili zote mbili moja kwa moja kwenye Netlify, weka ule wa siri kuwa siri):",
  ". Green = cheapest. Totals include freight; a supplier that didn't price every item shows how many it priced.": ". Kijani = bei nafuu zaidi. Jumla zinajumuisha usafirishaji; msambazaji ambaye hakuweka bei kwa kila bidhaa anaonyesha ameweka bei ngapi.",
  ". On iPhone the app must first be added to the Home Screen.": ". Kwenye iPhone programu lazima kwanza iongezwe kwenye Skrini ya Mwanzo.",
  ". Record payments on the invoice they pay.": ". Rekodi malipo kwenye ankara inayolipwa.",
  ". Rows without an ID get one automatically. If anything fails, nothing is saved.": ". Safu zisizo na ID zinapewa moja moja kwa moja. Kitu chochote kikishindikana, hakuna kinachohifadhiwa.",
  ". Search to narrow the list.": ". Tafuta ili kupunguza orodha.",
  ". The goods were returned to stock.": ". Bidhaa zilirudishwa kwenye stoku.",
  "0 is used automatically for exempt clients": "0 inatumika moja kwa moja kwa wateja waliosamehewa",
  "1. Choose the file": "1. Chagua faili",
  "1. Server key": "1. Ufunguo wa seva",
  "1. Server key (OUTBOX_SECRET)": "1. Ufunguo wa seva (OUTBOX_SECRET)",
  "2. Check what was found": "2. Kagua kilichopatikana",
  "2. Phone notifications": "2. Arifa za simu",
  "2. Phone notifications (VAPID keys)": "2. Arifa za simu (funguo za VAPID)",
  "3. Alert emails": "3. Barua pepe za tahadhari",
  "3. Email sending (Resend)": "3. Utumaji barua pepe (Resend)",
  "; new ones are": "; mpya ni",
  "Accepted": "Imekubaliwa",
  "Accepted client quotations with no supplier RFQ or PO yet.": "Nukuu za bei za wateja zilizokubaliwa bila RFQ ya msambazaji wala PO bado.",
  "Accepted this month (incl. VAT)": "Zilizokubaliwa mwezi huu (pamoja na VAT)",
  "Access": "Ufikiaji",
  "Account": "Akaunti",
  "Activity": "Shughuli",
  "Activity log": "Kumbukumbu ya shughuli",
  "Activity log shows every change. Export data downloads everything at any time.": "Kumbukumbu ya shughuli inaonyesha kila badiliko. Hamisha data hupakua kila kitu wakati wowote.",
  "Add a store": "Ongeza ghala",
  "Add bank details for quotations and invoices": "Ongeza maelezo ya benki kwa nukuu za bei na ankara",
  "Add client": "Ongeza mteja",
  "Add company details (TIN, address, phone)": "Ongeza maelezo ya kampuni (TIN, anwani, simu)",
  "Add contact": "Ongeza mtu wa mawasiliano",
  "Add cost": "Ongeza gharama",
  "Add duty, clearing, port charges, insurance and other costs for this order. They are shared over the items by value to give the true landed cost per unit.": "Ongeza ushuru, uondoshaji, ada za bandari, bima na gharama nyingine za oda hii. Zinagawanywa kwa bidhaa kulingana na thamani ili kupata gharama halisi ya kufikisha kwa kila kipimo.",
  "Add item": "Ongeza bidhaa",
  "Add new records": "Ongeza rekodi mpya",
  "Add or remove": "Ongeza au ondoa",
  "Add or update a rate": "Ongeza au sasisha kiwango",
  "Add product": "Ongeza bidhaa",
  "Add store": "Ongeza ghala",
  "Add supplier": "Ongeza msambazaji",
  "Add the client first:": "Ongeza mteja kwanza:",
  "Add the suppliers you want prices from.": "Ongeza wasambazaji unaotaka bei kutoka kwao.",
  "Add to Home Screen": "Ongeza kwenye Skrini ya Mwanzo",
  "Add to stock (+)": "Ongeza kwenye stoku (+)",
  "Add two more Netlify variables,": "Ongeza vigezo viwili zaidi vya Netlify,",
  "Added": "Imeongezwa",
  "Adding…": "Inaongeza…",
  "Address": "Anwani",
  "Adjust stock": "Rekebisha stoku",
  "After redeploying, each person opens": "Baada ya kusambaza upya, kila mtu anafungua",
  "Alert check running": "Ukaguzi wa tahadhari unaendelea",
  "Alert emails (Resend + your domain)": "Barua pepe za tahadhari (Resend + kikoa chako)",
  "Alerts": "Tahadhari",
  "Alerts setup": "Mipangilio ya tahadhari",
  "Alerts setup (server)": "Mipangilio ya tahadhari (seva)",
  "All": "Zote",
  "All RFQs →": "RFQ zote →",
  "All purchase orders": "Oda zote za ununuzi",
  "All quotations": "Nukuu zote za bei",
  "All stores": "Maghala yote",
  "All →": "Zote →",
  "Amount": "Kiasi",
  "Amount (": "Kiasi (",
  "Amount before VAT": "Kiasi kabla ya VAT",
  "An administrator can fix this by running the latest setup file in Supabase → SQL Editor.": "Msimamizi anaweza kurekebisha hili kwa kuendesha faili ya hivi karibuni ya usanidi katika Supabase → SQL Editor.",
  "An empty price uses the product's last cost (converted at this PO's exchange rate).": "Bei tupu inatumia gharama ya mwisho ya bidhaa (imebadilishwa kwa kiwango cha ubadilishaji cha PO hii).",
  "Applied": "Imetumika",
  "Applying…": "Inatumia…",
  "Approve": "Idhinisha",
  "Approved": "Imeidhinishwa",
  "Approved by": "Imeidhinishwa na",
  "Approved, not yet confirmed": "Imeidhinishwa, bado haijathibitishwa",
  "Archive client": "Hifadhi mteja kwenye kumbukumbu",
  "Archive product": "Hifadhi bidhaa kwenye kumbukumbu",
  "Archive supplier": "Hifadhi msambazaji kwenye kumbukumbu",
  "Archived": "Kwenye kumbukumbu",
  "Archived clients are hidden from lists but keep their history.": "Wateja waliohifadhiwa kwenye kumbukumbu hawaonekani kwenye orodha lakini historia yao inabaki.",
  "Ask suppliers for prices": "Uliza wasambazaji bei",
  "Assigned to": "Amekabidhiwa",
  "At or below reorder level": "Kwenye au chini ya kiwango cha kuagiza tena",
  "At the site": "Kwenye eneo la kazi",
  "Attention": "Tahadhari",
  "Attention (client contact)": "Kwa ajili ya (mtu wa mawasiliano wa mteja)",
  "Awaiting delivery": "Inasubiri uwasilishaji",
  "Award & create PO": "Toa zabuni na unda PO",
  "Awarded": "Imetolewa",
  "Back to sign in": "Rudi kwenye kuingia",
  "Balance due": "Salio linalodaiwa",
  "Bank details": "Maelezo ya benki",
  "Bank details for quotations and invoices": "Maelezo ya benki kwa nukuu za bei na ankara",
  "Bank details received": "Maelezo ya benki yamepokelewa",
  "Bank rate used": "Kiwango cha benki kilichotumika",
  "Bank ref, cheque no., M-Pesa code": "Kumb. ya benki, namba ya hundi, msimbo wa M-Pesa",
  "Batch": "Kundi",
  "Batch / lot no.": "Namba ya kundi / loti",
  "Batch no.": "Namba ya kundi",
  "Batches expiring within 60 days": "Makundi yanayoisha muda ndani ya siku 60",
  "Before you leave": "Kabla hujaondoka",
  "Being prepared": "Inaandaliwa",
  "Bill total": "Jumla ya bili",
  "Blank invoice": "Ankara tupu",
  "Brand": "Chapa",
  "Brands": "Chapa",
  "By client": "Kwa mteja",
  "By client and how late (aging)": "Kwa mteja na muda wa kuchelewa (umri wa deni)",
  "By currency": "Kwa sarafu",
  "By industry": "Kwa sekta",
  "By order": "Kwa oda",
  "By order, client, industry, salesperson": "Kwa oda, mteja, sekta, muuzaji",
  "By salesperson": "Kwa muuzaji",
  "By store and batch": "Kwa ghala na kundi",
  "By supplier and currency": "Kwa msambazaji na sarafu",
  "CAS no.": "Namba ya CAS",
  "Cancel": "Ghairi",
  "Cancel delivery note": "Ghairi hati ya uwasilishaji",
  "Cancel invoice": "Ghairi ankara",
  "Cancel purchase order": "Ghairi oda ya ununuzi",
  "Cancel quotation": "Ghairi nukuu ya bei",
  "Cancel this RFQ": "Ghairi RFQ hii",
  "Cancel this bill": "Ghairi bili hii",
  "Cancel this invoice": "Ghairi ankara hii",
  "Cancel this supplier RFQ": "Ghairi RFQ hii ya msambazaji",
  "Cancelled": "Imeghairiwa",
  "Cancelled.": "Imeghairiwa.",
  "Cancelling…": "Inaghairi…",
  "Catalogue prices are converted from": "Bei za katalogi zinabadilishwa kutoka",
  "Categories": "Makundi ya bidhaa",
  "Category": "Kundi la bidhaa",
  "Certificates held": "Vyeti vilivyopo",
  "Change password": "Badilisha nenosiri",
  "Chase late orders": "Fuatilia oda zilizochelewa",
  "Chase money": "Fuatilia madeni",
  "Check stock": "Kagua stoku",
  "Check the PO, Submit (large POs go to management), share the PDF with the supplier, then Supplier confirmed with their order number.": "Kagua PO, Wasilisha (PO kubwa zinaenda kwa uongozi), shiriki PDF na msambazaji, kisha Imethibitishwa na msambazaji pamoja na namba ya oda yao.",
  "Checking this device…": "Inakagua kifaa hiki…",
  "Checking…": "Inakagua…",
  "Choose": "Chagua",
  "Choose Could not deliver and say why. The goods go back into stock.": "Chagua Imeshindikana kuwasilisha na ueleze sababu. Bidhaa zinarudi kwenye stoku.",
  "Choose Excel file": "Chagua faili ya Excel",
  "Choose a client": "Chagua mteja",
  "Choose a different file": "Chagua faili nyingine",
  "Choose a product": "Chagua bidhaa",
  "Choose a role": "Chagua jukumu",
  "Choose a supplier": "Chagua msambazaji",
  "Choose a supplier to ask": "Chagua msambazaji wa kuuliza",
  "Choose the purchase order the delivery belongs to. Check quantities against the supplier's delivery note.": "Chagua oda ya ununuzi ambayo uwasilishaji huu ni wake. Linganisha idadi na hati ya uwasilishaji ya msambazaji.",
  "City": "Mji",
  "Client": "Mteja",
  "Client ID": "ID ya mteja",
  "Client RFQ": "RFQ ya mteja",
  "Client RFQ items": "Bidhaa za RFQ ya mteja",
  "Client RFQs": "RFQ za wateja",
  "Client RFQs, quotations, approvals": "RFQ za wateja, nukuu za bei, idhini",
  "Client accepted": "Mteja amekubali",
  "Client contact": "Mtu wa mawasiliano wa mteja",
  "Client contacts": "Watu wa mawasiliano wa mteja",
  "Client quotation": "Nukuu ya bei kwa mteja",
  "Client rejected": "Mteja amekataa",
  "Client's answer": "Jibu la mteja",
  "Client's answer:": "Jibu la mteja:",
  "Client's order / PO no.": "Namba ya oda / PO ya mteja",
  "Client's reference": "Kumbukumbu ya mteja",
  "Clients": "Wateja",
  "Clients pay within (days)": "Wateja hulipa ndani ya (siku)",
  "Clients, suppliers and products from the master data template": "Wateja, wasambazaji na bidhaa kutoka kiolezo cha data kuu",
  "Clients, suppliers and products loaded": "Wateja, wasambazaji na bidhaa zimepakiwa",
  "Closed": "Imefungwa",
  "Code": "Msimbo",
  "Collected in": "Imekusanywa ndani ya",
  "Collecting prices": "Inakusanya bei",
  "Colours": "Rangi",
  "Company": "Kampuni",
  "Company and documents": "Kampuni na nyaraka",
  "Company details": "Maelezo ya kampuni",
  "Company details & branding": "Maelezo ya kampuni na utambulisho",
  "Company details sets VAT, approval limits, minimum margin, payment days and the standard terms on documents.": "Maelezo ya kampuni huweka VAT, viwango vya idhini, faida ya chini, siku za malipo na masharti ya kawaida kwenye nyaraka.",
  "Company logo": "Nembo ya kampuni",
  "Company name": "Jina la kampuni",
  "Company rates for USD, EUR and other currencies": "Viwango vya kampuni kwa USD, EUR na sarafu nyingine",
  "Company rates for foreign currencies": "Viwango vya kampuni kwa sarafu za kigeni",
  "Company, industry, TIN/VRN, sites, terms": "Kampuni, sekta, TIN/VRN, maeneo, masharti",
  "Compare prices": "Linganisha bei",
  "Compare suppliers": "Linganisha wasambazaji",
  "Condition": "Hali",
  "Confirmed by supplier": "Imethibitishwa na msambazaji",
  "Confirmed delivery date": "Tarehe ya uwasilishaji iliyothibitishwa",
  "Confirming also updates each product's last cost from this PO.": "Kuthibitisha pia husasisha gharama ya mwisho ya kila bidhaa kutoka PO hii.",
  "Connect phone push and email sending": "Unganisha arifa za simu na utumaji barua pepe",
  "Connected": "Imeunganishwa",
  "Contact": "Mawasiliano",
  "Contact at site": "Mtu wa mawasiliano eneo la kazi",
  "Contact person": "Mtu wa mawasiliano",
  "Contact phone": "Simu ya mawasiliano",
  "Contact, country, currency, lead time, terms": "Mawasiliano, nchi, sarafu, muda wa kusubiri, masharti",
  "Contacts": "Watu wa mawasiliano",
  "Contacts, sites and history": "Mawasiliano, maeneo na historia",
  "Contacts, terms and lead times": "Mawasiliano, masharti na muda wa kusubiri",
  "Copying…": "Inanakili…",
  "Cost (known lines)": "Gharama (mistari inayojulikana)",
  "Cost of goods": "Gharama ya bidhaa",
  "Cost of goods sold": "Gharama ya bidhaa zilizouzwa",
  "Costs of this order that are not part of the goods: local transport, bank charges, commission…": "Gharama za oda hii ambazo si sehemu ya bidhaa: usafiri wa ndani, ada za benki, kamisheni…",
  "Costs on most products (for margins and profit)": "Gharama kwenye bidhaa nyingi (kwa faida na mapato)",
  "Could not deliver": "Imeshindikana kuwasilisha",
  "Country": "Nchi",
  "Country of origin": "Nchi ya asili",
  "Create a free account at": "Fungua akaunti ya bure kwenye",
  "Create account": "Fungua akaunti",
  "Create and add items": "Unda na ongeza bidhaa",
  "Create another quotation": "Unda nukuu ya bei nyingine",
  "Create blank invoice": "Unda ankara tupu",
  "Create company": "Unda kampuni",
  "Create delivery note": "Unda hati ya uwasilishaji",
  "Create draft PO": "Unda rasimu ya PO",
  "Create draft quotation": "Unda rasimu ya nukuu ya bei",
  "Create invoice": "Unda ankara",
  "Create purchase order": "Unda oda ya ununuzi",
  "Create quotation from these items": "Unda nukuu ya bei kutoka bidhaa hizi",
  "Create, issue and share invoices": "Unda, toa na shiriki ankara",
  "Creating PO…": "Inaunda PO…",
  "Creating…": "Inaunda…",
  "Credit": "Mkopo",
  "Credit available": "Mkopo unaopatikana",
  "Credit limit": "Kikomo cha mkopo",
  "Credit limit (TZS)": "Kikomo cha mkopo (TZS)",
  "Currencies": "Sarafu",
  "Currency": "Sarafu",
  "Current": "Ya sasa",
  "Damaged / rejected": "Imeharibika / imekataliwa",
  "Dark colour (top bar)": "Rangi nzito (upau wa juu)",
  "Date": "Tarehe",
  "Date paid": "Tarehe ya kulipa",
  "Date received": "Tarehe ya kupokea",
  "Declined": "Imekataliwa",
  "Deliver": "Wasilisha",
  "Deliver to": "Wasilisha kwa",
  "Delivered": "Imewasilishwa",
  "Delivered and ready to invoice.": "Imewasilishwa na iko tayari kwa ankara.",
  "Delivered but not invoiced": "Imewasilishwa lakini haijatolewa ankara",
  "Delivered, not invoiced yet.": "Imewasilishwa, bado haijatolewa ankara.",
  "Delivered, not yet invoiced (": "Imewasilishwa, bado haijatolewa ankara (",
  "Deliveries": "Uwasilishaji",
  "Deliveries assigned to you, record proof of delivery": "Uwasilishaji uliokabidhiwa kwako, rekodi uthibitisho wa uwasilishaji",
  "Deliveries late": "Uwasilishaji uliochelewa",
  "Deliveries to the client": "Uwasilishaji kwa mteja",
  "Delivery": "Uwasilishaji",
  "Delivery failed:": "Uwasilishaji umeshindikana:",
  "Delivery failed? Why": "Uwasilishaji umeshindikana? Kwa nini",
  "Delivery items": "Bidhaa za uwasilishaji",
  "Delivery notes": "Hati za uwasilishaji",
  "Delivery notes and proof of delivery": "Hati za uwasilishaji na uthibitisho wa uwasilishaji",
  "Delivery photo": "Picha ya uwasilishaji",
  "Delivery site / address": "Eneo / anwani ya uwasilishaji",
  "Delivery sites": "Maeneo ya uwasilishaji",
  "Delivery time": "Muda wa uwasilishaji",
  "Delivery to": "Uwasilishaji kwa",
  "Description": "Maelezo",
  "Details": "Taarifa",
  "Details for support:": "Taarifa kwa msaada:",
  "Disc. %": "Punguzo %",
  "Discount %": "Punguzo %",
  "Discounts": "Punguzo",
  "Dispatch now": "Tuma sasa",
  "Dispatching takes the goods out of": "Kutuma kunatoa bidhaa kutoka",
  "Dispatching…": "Inatuma…",
  "Done": "Imekamilika",
  "Download everything (one JSON file)": "Pakua kila kitu (faili moja la JSON)",
  "Download everything as Excel (CSV) or one backup file": "Pakua kila kitu kama Excel (CSV) au faili moja la nakala rudufu",
  "Download the blank template": "Pakua kiolezo kitupu",
  "Download the template": "Pakua kiolezo",
  "Draft": "Rasimu",
  "Draft invoice": "Rasimu ya ankara",
  "Draft invoices to issue": "Rasimu za ankara za kutoa",
  "Drafts": "Rasimu",
  "Drafts, approvals, confirmations": "Rasimu, idhini, uthibitisho",
  "Driver": "Dereva",
  "Driver and vehicle": "Dereva na gari",
  "Due ": "Tarehe ya mwisho ",
  "Due date": "Tarehe ya mwisho",
  "Each person gets at most one email every 5 minutes, listing their new urgent alerts. Anyone can switch emails off for themselves.": "Kila mtu hupata barua pepe moja tu kila dakika 5, ikiorodhesha arifa zake mpya za dharura. Mtu yeyote anaweza kuzima barua pepe kwa ajili yake.",
  "Edit RFQ details": "Hariri taarifa za RFQ",
  "Edit details": "Hariri taarifa",
  "Edit prices": "Hariri bei",
  "Email": "Barua pepe",
  "Emails to": "Barua pepe kwa",
  "Enter prices": "Weka bei",
  "Enter the quantity received now (leave 0 for items that didn't come). Damaged items are recorded but not added to stock.": "Weka idadi iliyopokelewa sasa (acha 0 kwa vitu ambavyo havikufika). Vitu vilivyoharibika vinarekodiwa lakini haviongezwi kwenye stoku.",
  "Enter the supplier's invoice as you received it.": "Weka ankara ya msambazaji kama ulivyoipokea.",
  "Enter your email and we'll send you a link to set a new password.": "Weka barua pepe yako na tutakutumia kiungo cha kuweka nenosiri jipya.",
  "Estimated margin": "Faida inayokadiriwa",
  "Every change to settings, the team, clients, suppliers and products, newest first. This record cannot be edited.": "Kila mabadiliko ya mipangilio, timu, wateja, wasambazaji na bidhaa, ya karibuni kwanza. Kumbukumbu hii haiwezi kuhaririwa.",
  "Every change, who made it and when": "Kila mabadiliko, nani aliyafanya na lini",
  "Every list has search; every document has a PDF you can share by WhatsApp or email.": "Kila orodha ina utafutaji; kila hati ina PDF unayoweza kushiriki kwa WhatsApp au barua pepe.",
  "Everything appears here. Urgent things (approvals, new RFQs, deliveries, overdue invoices, expiring stock) can also reach your phone and email.": "Kila kitu kinaonekana hapa. Mambo ya dharura (idhini, RFQ mpya, uwasilishaji, ankara zilizochelewa, stoku inayokwisha muda) yanaweza pia kufika kwenye simu na barua pepe yako.",
  "Exchange rate": "Kiwango cha ubadilishaji",
  "Exchange rate on the day": "Kiwango cha ubadilishaji cha siku hiyo",
  "Exchange rates": "Viwango vya ubadilishaji",
  "Exchange rates for every foreign currency you use": "Viwango vya ubadilishaji kwa kila sarafu ya kigeni unayotumia",
  "Expected deliveries": "Uwasilishaji unaotarajiwa",
  "Expiring soon": "Inakwisha muda karibuni",
  "Expiry date": "Tarehe ya kwisha muda",
  "Export all data →": "Hamisha data yote →",
  "Export data": "Hamisha data",
  "Export your data": "Hamisha data yako",
  "Failed": "Imeshindwa",
  "Failed / cancelled": "Imeshindwa / imeghairiwa",
  "Fill in a form directly in the app, one record at a time.": "Jaza fomu moja kwa moja kwenye programu, rekodi moja baada ya nyingine.",
  "Filter": "Chuja",
  "Finance": "Fedha",
  "Fix": "Rekebisha",
  "Follow up": "Fuatilia",
  "Footer text": "Maandishi ya chini",
  "For": "Kwa",
  "For a quotation that answers a client RFQ, open the RFQ and use “Create quotation” instead, so the items are copied across.": "Kwa nukuu ya bei inayojibu RFQ ya mteja, fungua RFQ na utumie “Create quotation” badala yake, ili vitu vinakiliwe.",
  "For client quotation": "Kwa nukuu ya bei ya mteja",
  "Forgot your password?": "Umesahau nenosiri?",
  "Former team member": "Mwanatimu wa zamani",
  "Freight": "Usafirishaji",
  "Freight / delivery charge (their currency)": "Gharama ya usafirishaji / uwasilishaji (sarafu yao)",
  "From": "Kutoka",
  "From product": "Kutoka bidhaa",
  "From store": "Kutoka ghala",
  "From the RFQ press Create quotation. Pick products from the catalogue, set prices and discounts, check delivery time and payment terms.": "Kutoka kwenye RFQ bonyeza Create quotation. Chagua bidhaa kutoka katalogi, weka bei na punguzo, hakiki muda wa uwasilishaji na masharti ya malipo.",
  "Full name": "Jina kamili",
  "Generate a key pair": "Tengeneza jozi ya funguo",
  "GitHub repository set to private": "Hazina ya GitHub imewekwa kuwa ya faragha",
  "Go-live checklist": "Orodha ya ukaguzi kabla ya kuanza",
  "Good": "Nzuri",
  "Goods received": "Bidhaa zilizopokelewa",
  "Goods received items": "Vitu vya bidhaa zilizopokelewa",
  "Goods received notes": "Hati za kupokea bidhaa (GRN)",
  "Gross profit": "Faida ghafi",
  "Has access": "Ana ruhusa",
  "Hazardous": "Hatari",
  "Help": "Msaada",
  "Hide": "Ficha",
  "Hide password": "Ficha nenosiri",
  "Home": "Nyumbani",
  "Hosting and safety": "Uhifadhi na usalama",
  "How": "Jinsi",
  "How many": "Ngapi",
  "How you are told": "Jinsi unavyoarifiwa",
  "I have sent it to the client": "Nimemtumia mteja",
  "I have sent it to the supplier": "Nimemtumia msambazaji",
  "If an account exists for that email, we've sent a link. Open it on this device to choose a new password.": "Ikiwa akaunti ipo kwa barua pepe hiyo, tumetuma kiungo. Kifungue kwenye kifaa hiki kuchagua nenosiri jipya.",
  "If you generate again, the old pair stops working and everyone has to turn notifications on again.": "Ukitengeneza tena, jozi ya zamani itaacha kufanya kazi na kila mtu atalazimika kuwasha arifa upya.",
  "Import": "Ingiza",
  "Import costs": "Gharama za uagizaji",
  "Import costs & landed cost": "Gharama za uagizaji na gharama halisi (landed cost)",
  "Import from spreadsheet": "Ingiza kutoka lahajedwali",
  "Importing…": "Inaingiza…",
  "In progress": "Inaendelea",
  "In use": "Inatumika",
  "Include products with no stock": "Jumuisha bidhaa zisizo na stoku",
  "Industries": "Sekta",
  "Industry": "Sekta",
  "Install the app: on Android, Chrome menu → Add to Home screen; on iPhone, Safari Share → Add to Home Screen.": "Sakinisha programu: kwenye Android, menyu ya Chrome → Add to Home screen; kwenye iPhone, Safari Share → Add to Home Screen.",
  "Into store": "Kwenda ghala",
  "Invite": "Alika",
  "Invite 2–3 suppliers, share the RFQ PDF with each, enter their prices when they reply, then Compare prices and Award & create PO.": "Alika wasambazaji 2–3, shiriki PDF ya RFQ na kila mmoja, weka bei zao wanapojibu, kisha Compare prices na Award & create PO.",
  "Invite people with the right role; switch access off the day someone leaves.": "Alika watu wenye jukumu sahihi; zima ruhusa siku mtu anapoondoka.",
  "Invite people, change roles": "Alika watu, badilisha majukumu",
  "Invite people, change roles, switch access off": "Alika watu, badilisha majukumu, zima ruhusa",
  "Invite someone": "Alika mtu",
  "Invite your team": "Alika timu yako",
  "Inviting…": "Inaalika…",
  "Invoice": "Ankara",
  "Invoice date": "Tarehe ya ankara",
  "Invoice deliveries": "Toa ankara za uwasilishaji",
  "Invoice it": "Toa ankara",
  "Invoice items": "Vitu vya ankara",
  "Invoice no. or client's PO no.": "Namba ya ankara au namba ya PO ya mteja",
  "Invoice the rest": "Toa ankara ya kilichobaki",
  "Invoice total": "Jumla ya ankara",
  "Invoiced": "Imetolewa ankara",
  "Invoiced (before VAT)": "Imetolewa ankara (kabla ya VAT)",
  "Invoiced in": "Imetolewa ankara",
  "Invoiced:": "Imetolewa ankara:",
  "Invoices": "Ankara",
  "Invoices and what clients owe": "Ankara na madeni ya wateja",
  "Invoices, payments, money owed, profit": "Ankara, malipo, madeni, faida",
  "Issue date": "Tarehe ya kutolewa",
  "Issue invoice": "Toa ankara",
  "Issued": "Imetolewa",
  "Issued above the client's credit limit, approved by": "Imetolewa juu ya kikomo cha mkopo cha mteja, imeidhinishwa na",
  "Issuing gives the invoice its number and due date and locks it. If it takes the client above their credit limit, only management can issue it.": "Kutoa kunaipa ankara namba yake na tarehe ya mwisho na kuifunga. Ikimfanya mteja kuzidi kikomo chake cha mkopo, ni uongozi pekee unaoweza kuitoa.",
  "Issuing…": "Inatoa…",
  "It is saved on your phone and sent automatically when you have signal again. You can also press Send now.": "Imehifadhiwa kwenye simu yako na itatumwa yenyewe mtandao ukirudi. Unaweza pia kubonyeza Send now.",
  "Item": "Kitu",
  "Items (": "Vitu (",
  "Items requested (": "Vitu vilivyoombwa (",
  "Join": "Jiunge",
  "Joining a company? Create your account with the same email address your manager invited.": "Unajiunga na kampuni? Fungua akaunti yako kwa barua pepe ile ile aliyokualikia meneja wako.",
  "Joining…": "Inajiunga…",
  "Keep the company USD/EUR rates up to date. Documents in foreign currency use them automatically.": "Weka viwango vya USD/EUR vya kampuni kuwa vya sasa. Hati za sarafu za kigeni huvitumia moja kwa moja.",
  "Landed / unit": "Gharama halisi / kipimo",
  "Last alert check:": "Ukaguzi wa mwisho wa arifa:",
  "Last cost": "Gharama ya mwisho",
  "Last cost (": "Gharama ya mwisho (",
  "Later →": "Baadaye →",
  "LeMoSp · a LeMo Tech Solutions product": "LeMoSp · bidhaa ya LeMo Tech Solutions",
  "Lead time": "Muda wa kusubiri",
  "Lead time (days)": "Muda wa kusubiri (siku)",
  "Leave empty for the standard PO terms": "Acha wazi kwa masharti ya kawaida ya PO",
  "Limits and terms": "Vikomo na masharti",
  "Lines without a cost": "Mistari isiyo na gharama",
  "Load clients, suppliers and products from the master data template in one go. You can import again later: records with the same ID or SKU are updated, not duplicated.": "Pakia wateja, wasambazaji na bidhaa kutoka kiolezo cha data kuu kwa mara moja. Unaweza kuingiza tena baadaye: rekodi zenye ID au SKU ile ile zinasasishwa, hazirudiwi.",
  "Load many records at once from the template": "Pakia rekodi nyingi kwa mara moja kutoka kiolezo",
  "Load opening stock": "Pakia stoku ya mwanzo",
  "Load your clients, suppliers and products": "Pakia wateja, wasambazaji na bidhaa zako",
  "Loaded": "Imepakiwa",
  "Loading…": "Inapakia…",
  "Location": "Mahali",
  "Log every request": "Rekodi kila ombi",
  "Logo": "Nembo",
  "Logo uploaded and colours set": "Nembo imepakiwa na rangi zimewekwa",
  "Lost": "Imepotea",
  "Lost / cancelled": "Imepotea / imeghairiwa",
  "Main": "Kuu",
  "Main colour": "Rangi kuu",
  "Main currency": "Sarafu kuu",
  "Main supplier": "Msambazaji mkuu",
  "Main supplier for": "Msambazaji mkuu wa",
  "Main supplier:": "Msambazaji mkuu:",
  "Make a revision": "Tengeneza toleo jipya",
  "Manufacturer": "Mtengenezaji",
  "Manufacturer part no.": "Namba ya sehemu ya mtengenezaji",
  "Margin": "Faida",
  "Margin at submission": "Faida wakati wa kuwasilisha",
  "Mark all read": "Weka zote kuwa zimesomwa",
  "Me": "Mimi",
  "Minimum margin %": "Kiwango cha chini cha faida %",
  "Minimum order": "Oda ya chini",
  "Money in, with receipts": "Pesa zilizoingia, pamoja na stakabadhi",
  "Money owed to us": "Madeni ya wateja",
  "Money owed to us shows every client by how late they are. The bell reminds you at 1, 30, 60 and 90 days overdue.": "Madeni ya wateja yanaonyesha kila mteja kulingana na amechelewa kiasi gani. Kengele inakukumbusha siku 1, 30, 60 na 90 baada ya kuchelewa.",
  "Money we owe": "Madeni ya wasambazaji",
  "Month": "Mwezi",
  "More": "Zaidi",
  "Most overdue": "Zilizochelewa zaidi",
  "Movements": "Mienendo",
  "My deliveries": "Uwasilishaji wangu",
  "NEXT_PUBLIC_SITE_URL matches the web address": "NEXT_PUBLIC_SITE_URL inalingana na anwani ya tovuti",
  "Name": "Jina",
  "Name, TIN, VRN, logo, colours, bank details": "Jina, TIN, VRN, nembo, rangi, taarifa za benki",
  "Need supplier prices before quoting? Send these items to suppliers.": "Unahitaji bei za wasambazaji kabla ya kutoa nukuu ya bei? Tuma vitu hivi kwa wasambazaji.",
  "New": "Mpya",
  "New RFQ": "RFQ mpya",
  "New client": "Mteja mpya",
  "New client RFQ": "RFQ mpya ya mteja",
  "New delivery note": "Hati mpya ya uwasilishaji",
  "New invoice": "Ankara mpya",
  "New password": "Nenosiri jipya",
  "New product": "Bidhaa mpya",
  "New purchase order": "Oda mpya ya ununuzi",
  "New quotation": "Nukuu mpya ya bei",
  "New supplier": "Msambazaji mpya",
  "New supplier RFQ": "RFQ mpya kwa msambazaji",
  "New supplier bill": "Bili mpya ya msambazaji",
  "Next:": "Inayofuata:",
  "Nightly encrypted database backup set up in GitHub": "Nakala rudufu ya kila usiku ya hifadhidata iliyosimbwa imewekwa kwenye GitHub",
  "No": "Hapana",
  "No RFQs here.": "Hakuna RFQ hapa.",
  "No batch": "Hakuna bechi",
  "No bills here. Record a supplier's invoice from its purchase order, or with “+ Bill”.": "Hakuna bili hapa. Rekodi ankara ya msambazaji kutoka kwenye oda yake ya ununuzi, au kwa “+ Bill”.",
  "No clients match your search.": "Hakuna wateja wanaolingana na utafutaji wako.",
  "No clients yet.": "Bado hakuna wateja.",
  "No contacts yet.": "Bado hakuna watu wa mawasiliano.",
  "No deliveries here. Delivery notes are usually created from an accepted quotation.": "Hakuna uwasilishaji hapa. Hati za uwasilishaji kwa kawaida hutengenezwa kutoka nukuu ya bei iliyokubaliwa.",
  "No delivery notes yet.": "Bado hakuna hati za uwasilishaji.",
  "No extra costs recorded.": "Hakuna gharama za ziada zilizorekodiwa.",
  "No foreign currencies yet. Add one before quoting, buying or invoicing in it.": "Bado hakuna sarafu za kigeni. Ongeza moja kabla ya kutoa nukuu ya bei, kununua au kutoa ankara kwa sarafu hiyo.",
  "No invoices here. Invoices are usually created from an accepted quotation or a delivered delivery note.": "Hakuna ankara hapa. Ankara kwa kawaida hutengenezwa kutoka nukuu ya bei iliyokubaliwa au hati ya uwasilishaji iliyowasilishwa.",
  "No invoices issued in": "Hakuna ankara zilizotolewa",
  "No items yet.": "Bado hakuna vitu.",
  "No logo": "Hakuna nembo",
  "No movements yet.": "Bado hakuna mienendo.",
  "No payments recorded in": "Hakuna malipo yaliyorekodiwa",
  "No products match your search.": "Hakuna bidhaa zinazolingana na utafutaji wako.",
  "No products yet.": "Bado hakuna bidhaa.",
  "No purchase orders are waiting for delivery.": "Hakuna oda za ununuzi zinazosubiri kuwasilishwa.",
  "No purchase orders here.": "Hakuna oda za ununuzi hapa.",
  "No quotation yet.": "Bado hakuna nukuu ya bei.",
  "No quotations here.": "Hakuna nukuu za bei hapa.",
  "No rows filled in": "Hakuna mistari iliyojazwa",
  "No rows to import. The grey example rows are skipped automatically.": "Hakuna mistari ya kuingiza. Mistari ya mfano ya kijivu inarukwa yenyewe.",
  "No signal?": "Hakuna mtandao?",
  "No supplier invoice recorded yet.": "Bado hakuna ankara ya msambazaji iliyorekodiwa.",
  "No suppliers match your search.": "Hakuna wasambazaji wanaolingana na utafutaji wako.",
  "No suppliers yet.": "Bado hakuna wasambazaji.",
  "None": "Hakuna",
  "None in stock.": "Hakuna kwenye stoku.",
  "Not assigned": "Hajapangiwa",
  "Not invoiced yet.": "Bado haijatolewa ankara.",
  "Not set": "Haijawekwa",
  "Note": "Dokezo",
  "Notes": "Madokezo",
  "Notes for suppliers": "Madokezo kwa wasambazaji",
  "Notes for the driver and client": "Madokezo kwa dereva na mteja",
  "Notes to the client": "Madokezo kwa mteja",
  "Notes to the supplier": "Madokezo kwa msambazaji",
  "Nothing here.": "Hakuna kitu hapa.",
  "Nothing in stock here yet. Stock arrives when you receive goods against a purchase order, or through an adjustment (opening balance).": "Bado hakuna stoku hapa. Stoku huingia unapopokea bidhaa dhidi ya oda ya ununuzi, au kupitia marekebisho (salio la mwanzo).",
  "Nothing left to receive on this purchase order.": "Hakuna kilichobaki kupokelewa kwenye oda hii ya ununuzi.",
  "Nothing on order.": "Hakuna kilichoagizwa.",
  "Nothing outstanding.": "Hakuna kinachodaiwa.",
  "Nothing received yet.": "Bado hakuna kilichopokelewa.",
  "Nothing recorded yet.": "Bado hakuna kilichorekodiwa.",
  "Nothing waiting. Delivered delivery notes appear here until they are invoiced.": "Hakuna kinachosubiri. Hati za uwasilishaji zilizowasilishwa zinaonekana hapa hadi zitolewe ankara.",
  "Nothing waiting. New client requests will appear here.": "Hakuna kinachosubiri. Maombi mapya ya wateja yataonekana hapa.",
  "Nothing yet. You'll be told here when something needs you: approvals, new RFQs, deliveries, overdue invoices, stock alerts.": "Bado hakuna kitu. Utaarifiwa hapa kitu kikihitaji hatua yako: idhini, RFQ mpya, uwasilishaji, ankara zilizochelewa, arifa za stoku.",
  "Notifications": "Arifa",
  "Notifications always appear in the app (the bell at the top). This page connects the extras: phone notifications and alert emails, and the background job that checks for overdue invoices, expiring stock and so on every 5 minutes.": "Arifa huonekana kila mara kwenye programu (kengele juu). Ukurasa huu unaunganisha ziada: arifa za simu na barua pepe za arifa, pamoja na kazi ya nyuma inayokagua ankara zilizochelewa, stoku inayokwisha muda na mengineyo kila dakika 5.",
  "Notifications are blocked for this site. Allow them in your browser or phone settings, then reload.": "Arifa zimezuiwa kwa tovuti hii. Ziruhusu kwenye mipangilio ya kivinjari au simu yako, kisha pakia upya.",
  "Notifications are not switched on yet. Management needs to run the Stage 7 database update.": "Arifa bado hazijawashwa. Uongozi unahitaji kuendesha sasisho la hifadhidata la Hatua ya 7.",
  "Offer valid until": "Ofa ni halali hadi",
  "On for this device": "Imewashwa kwa kifaa hiki",
  "On iPhone, first add the app to your Home Screen: tap": "Kwenye iPhone, kwanza ongeza programu kwenye Home Screen: gusa",
  "On the PO add duty, clearing, port charges and freight, then Use landed cost as product cost so margins are real.": "Kwenye PO ongeza ushuru, gharama za uondoshaji, gharama za bandari na usafirishaji, kisha Use landed cost as product cost ili faida ziwe halisi.",
  "On the invoice, Record a payment received (part or full). Each payment has a receipt PDF.": "Kwenye ankara, Record a payment received (sehemu au kamili). Kila malipo yana PDF ya stakabadhi.",
  "On the way": "Njiani",
  "On your documents": "Kwenye hati zako",
  "One table at a time (CSV for Excel)": "Jedwali moja kwa wakati (CSV kwa Excel)",
  "Only management and finance can change them.": "Ni uongozi na fedha pekee wanaoweza kuvibadilisha.",
  "Only management and finance see this. Costs are the product costs when the invoice was issued.": "Ni uongozi na fedha pekee wanaoona hii. Gharama ni gharama za bidhaa wakati ankara ilipotolewa.",
  "Only management can change these details.": "Ni uongozi pekee unaoweza kubadilisha taarifa hizi.",
  "Only management, procurement and finance can see this.": "Ni uongozi, ununuzi na fedha pekee wanaoweza kuona hii.",
  "Open": "Fungua",
  "Open My deliveries while you have signal, so the list is saved on your phone.": "Fungua Uwasilishaji wangu ukiwa na mtandao, ili orodha ihifadhiwe kwenye simu yako.",
  "Open PDF": "Fungua PDF",
  "Open RFQ PDF": "Fungua PDF ya RFQ",
  "Open the delivery note (from the accepted order), set store, site, driver and vehicle, then Dispatch. Stock goes out oldest-expiry first.": "Fungua hati ya uwasilishaji (kutoka oda iliyokubaliwa), weka ghala, eneo, dereva na gari, kisha Dispatch. Stoku hutoka kwa zile zinazokwisha muda mapema kwanza.",
  "Opening stock loaded": "Stoku ya mwanzo imepakiwa",
  "Or set up a new company": "Au anzisha kampuni mpya",
  "Order and import costs": "Gharama za oda na uagizaji",
  "Order costs": "Gharama za oda",
  "Order date": "Tarehe ya oda",
  "Order progress": "Maendeleo ya oda",
  "Ordered": "Imeagizwa",
  "Other": "Nyingine",
  "Other order costs": "Gharama nyingine za oda",
  "Other order costs (transport, bank…)": "Gharama nyingine za oda (usafiri, benki…)",
  "Other roles": "Majukumu mengine",
  "Our store": "Ghala letu",
  "Our vendor status with them": "Hali yetu ya usajili kama msambazaji kwao",
  "Overdue": "Imechelewa",
  "Overdue ·": "Imechelewa ·",
  "Overdue · ": "Imechelewa · ",
  "Owed to us": "Tunadai",
  "PNG, JPG or WebP, under 1 MB. A square logo on a white or transparent background works best.": "PNG, JPG au WebP, chini ya MB 1. Nembo ya mraba yenye mandharinyuma meupe au angavu inafaa zaidi.",
  "POs above": "PO zaidi ya",
  "POs waiting for approval": "PO zinazosubiri idhini",
  "POs waiting for your approval": "PO zinazosubiri idhini yako",
  "Pack size": "Ukubwa wa kifungashio",
  "Paid": "Imelipwa",
  "Part paid": "Imelipwa kiasi",
  "Partly received": "Imepokelewa kiasi",
  "Password": "Nenosiri",
  "Paste the": "Bandika",
  "Pay suppliers": "Lipa wasambazaji",
  "Payment": "Malipo",
  "Payment terms": "Masharti ya malipo",
  "Payments": "Malipo",
  "Payments received": "Malipo yaliyopokelewa",
  "Payments to suppliers": "Malipo kwa wasambazaji",
  "People": "Watu",
  "Phone": "Simu",
  "Phone / WhatsApp": "Simu / WhatsApp",
  "Phone call": "Simu",
  "Phone notifications": "Arifa za simu",
  "Phone notifications (VAPID keys)": "Arifa za simu (funguo za VAPID)",
  "Phone notifications and alert emails for you": "Arifa za simu na barua pepe za tahadhari kwako",
  "Phone notifications are not set up on the server yet (ask management).": "Arifa za simu bado hazijawekwa kwenye seva (uliza uongozi).",
  "Photo": "Picha",
  "Physical address": "Anwani ya mahali",
  "Planned date": "Tarehe iliyopangwa",
  "Please wait…": "Tafadhali subiri…",
  "Position": "Cheo",
  "Preparing…": "Inaandaliwa…",
  "Press Record delivery. Type the receiver's name, ask them to sign on the screen, take a photo of the goods, then Confirm delivery.": "Bonyeza Rekodi uwasilishaji. Andika jina la mpokeaji, mwombe asaini kwenye skrini, piga picha ya bidhaa, kisha Thibitisha uwasilishaji.",
  "Press Run, and wait for “Success. No rows returned”": "Bonyeza Run, kisha subiri “Success. No rows returned”",
  "Preview PDF": "Hakiki PDF",
  "Price (": "Bei (",
  "Price received": "Bei iliyopokelewa",
  "Prices from": "Bei kutoka",
  "Print": "Chapisha",
  "Print delivery note": "Chapisha hati ya uwasilishaji",
  "Printed on the RFQ PDF": "Huchapishwa kwenye PDF ya RFQ",
  "Printed on the delivery note": "Huchapishwa kwenye hati ya uwasilishaji",
  "Product": "Bidhaa",
  "Product costs": "Gharama za bidhaa",
  "Product details": "Maelezo ya bidhaa",
  "Product name": "Jina la bidhaa",
  "Products": "Bidhaa",
  "Products in stock": "Bidhaa zilizo kwenye stoku",
  "Products supplied": "Bidhaa zinazosambazwa",
  "Profit": "Faida",
  "Profit on this invoice": "Faida kwenye ankara hii",
  "Profit shows the month by order, client, industry and salesperson.": "Faida inaonyesha mwezi kwa oda, mteja, sekta na muuzaji.",
  "Proof of delivery": "Uthibitisho wa uwasilishaji",
  "Public sign-up of new companies switched off": "Usajili wa wazi wa kampuni mpya umezimwa",
  "Purchase order": "Oda ya ununuzi",
  "Purchase order items": "Vipengee vya oda ya ununuzi",
  "Purchase orders": "Oda za ununuzi",
  "Purchasing": "Ununuzi",
  "Purchasing for this order": "Ununuzi kwa oda hii",
  "Qty": "Idadi",
  "Quantity": "Kiasi",
  "Quantity received": "Kiasi kilichopokelewa",
  "Quotation": "Nukuu ya bei",
  "Quotation items": "Vipengee vya nukuu ya bei",
  "Quotations": "Nukuu za bei",
  "Quotations and POs above the limits wait for you (you are told on the bell and phone). Nobody can approve their own.": "Nukuu za bei na PO zinazozidi viwango zinakusubiri (utaarifiwa kwenye kengele na simu). Hakuna anayeweza kuidhinisha yake mwenyewe.",
  "Quotations valid for (days)": "Muda wa nukuu za bei (siku)",
  "Quote": "Toa bei",
  "Quote due by": "Bei itolewe kabla ya",
  "Quoted": "Bei imetolewa",
  "Quoting": "Inaandaliwa bei",
  "RFQs": "RFQ",
  "RFQs to answer": "RFQ za kujibu",
  "Re-apply landed cost": "Tumia upya gharama halisi ya kufikisha",
  "Reading…": "Inasoma…",
  "Reason": "Sababu",
  "Reason, e.g. cheque bounced": "Sababu, mf. cheque bounced",
  "Receipt": "Risiti",
  "Receive from": "Pokea kutoka",
  "Receive goods": "Pokea bidhaa",
  "Receive goods lists POs waiting for delivery. Enter what arrived, with batch numbers and expiry dates for chemicals and lubricants.": "Pokea bidhaa inaorodhesha PO zinazosubiri kuwasilishwa. Ingiza kilichofika, pamoja na namba za bechi na tarehe za kuisha muda kwa kemikali na vilainishi.",
  "Received": "Imepokelewa",
  "Received / closed": "Imepokelewa / imefungwa",
  "Received by": "Imepokelewa na",
  "Received on": "Ilipokelewa tarehe",
  "Recently received": "Zilizopokelewa hivi karibuni",
  "Record a request for quotation from a client. You'll add the items next.": "Rekodi ombi la nukuu ya bei kutoka kwa mteja. Utaongeza vipengee baadaye.",
  "Record a supplier bill": "Rekodi bili ya msambazaji",
  "Record and pay suppliers' invoices": "Rekodi na lipa ankara za wasambazaji",
  "Record each supplier's invoice from its PO, then record payments. Money we owe shows totals per currency.": "Rekodi ankara ya kila msambazaji kutoka kwenye PO yake, kisha rekodi malipo. Pesa tunazodaiwa zinaonyesha jumla kwa kila sarafu.",
  "Record failed delivery": "Rekodi uwasilishaji ulioshindikana",
  "Record goods arriving against purchase orders": "Rekodi bidhaa zinazofika dhidi ya oda za ununuzi",
  "Record goods received": "Rekodi bidhaa zilizopokelewa",
  "Record payment": "Rekodi malipo",
  "Record payments": "Rekodi malipo",
  "Record proof of delivery": "Rekodi uthibitisho wa uwasilishaji",
  "Record supplier's invoice": "Rekodi ankara ya msambazaji",
  "Record the answer": "Rekodi jibu",
  "Recorded by": "Imerekodiwa na",
  "Records": "Kumbukumbu",
  "Records and backups": "Kumbukumbu na nakala rudufu",
  "Reference": "Kumbukumbu namba",
  "Region": "Mkoa",
  "Registered name": "Jina lililosajiliwa",
  "Registration": "Usajili",
  "Registration no. (BRELA)": "Namba ya usajili (BRELA)",
  "Registration number": "Namba ya usajili",
  "Rejected": "Imekataliwa",
  "Rejected / cancelled": "Imekataliwa / imeghairiwa",
  "Reload": "Pakia upya",
  "Remarks": "Maoni",
  "Remove": "Ondoa",
  "Remove from stock (−)": "Ondoa kwenye stoku (−)",
  "Removing…": "Inaondoa…",
  "Reorder": "Agiza tena",
  "Reorder level": "Kiwango cha kuagiza tena",
  "Replace logo": "Badilisha nembo",
  "Replaced by revision": "Imebadilishwa na marekebisho",
  "Reply by": "Jibu kabla ya",
  "Request supplier quotes": "Omba bei kwa wasambazaji",
  "Required by": "Inahitajika kabla ya",
  "Reset your password": "Weka upya nenosiri lako",
  "Restore client": "Rejesha mteja",
  "Restore product": "Rejesha bidhaa",
  "Restore supplier": "Rejesha msambazaji",
  "Role": "Jukumu",
  "Run the check and send now": "Fanya ukaguzi na tuma sasa",
  "Running…": "Inaendesha…",
  "SDS on file": "SDS ipo kwenye faili",
  "SKU, brand, part number, unit, price, safety": "SKU, chapa, namba ya kipuri, kipimo, bei, usalama",
  "Safety & compliance": "Usalama na uzingatiaji",
  "Sales": "Mauzo",
  "Sales (before VAT)": "Mauzo (kabla ya VAT)",
  "Sales and gross profit by month": "Mauzo na faida ghafi kwa mwezi",
  "Sales are issued invoices in": "Mauzo ni ankara zilizotolewa katika",
  "Sales invoiced (before VAT)": "Mauzo yaliyotolewa ankara (kabla ya VAT)",
  "Sales · Procurement · Stock · Delivery · Finance": "Mauzo · Ununuzi · Stoku · Uwasilishaji · Fedha",
  "Save": "Hifadhi",
  "Save RFQ": "Hifadhi RFQ",
  "Save adjustment": "Hifadhi marekebisho",
  "Save bill": "Hifadhi bili",
  "Save changes": "Hifadhi mabadiliko",
  "Save company details": "Hifadhi taarifa za kampuni",
  "Save details": "Hifadhi taarifa",
  "Save prices": "Hifadhi bei",
  "Save purchasing details": "Hifadhi taarifa za ununuzi",
  "Save rate": "Hifadhi kiwango",
  "Saving…": "Inahifadhi…",
  "Search": "Tafuta",
  "Search PO no. or supplier ref…": "Tafuta namba ya PO au kumbukumbu ya msambazaji…",
  "Search number, title, client ref…": "Tafuta namba, kichwa, kumbukumbu ya mteja…",
  "Search product or SKU…": "Tafuta bidhaa au SKU…",
  "Search quotation no. or client ref…": "Tafuta namba ya nukuu ya bei au kumbukumbu ya mteja…",
  "Search, view and edit clients and their contacts": "Tafuta, tazama na hariri wateja na mawasiliano yao",
  "Search, view and edit suppliers": "Tafuta, tazama na hariri wasambazaji",
  "Search, view and edit the catalogue": "Tafuta, tazama na hariri katalogi",
  "Search…": "Tafuta…",
  "Second currency": "Sarafu ya pili",
  "Sections": "Sehemu",
  "See all supplier bills →": "Tazama bili zote za wasambazaji →",
  "See overdue invoices →": "Tazama ankara zilizochelewa →",
  "See stock →": "Tazama stoku →",
  "Selling": "Mauzo",
  "Selling price (TZS)": "Bei ya kuuza (TZS)",
  "Send": "Tuma",
  "Send back for changes": "Rudisha kwa marekebisho",
  "Send me a test": "Nitumie jaribio",
  "Send reset link": "Tuma kiungo cha kuweka upya",
  "Sending…": "Inatuma…",
  "Sent": "Imetumwa",
  "Sent back by management:": "Imerudishwa na uongozi:",
  "Sent to client": "Imetumwa kwa mteja",
  "Sent to supplier": "Imetumwa kwa msambazaji",
  "Sent, awaiting answer": "Imetumwa, inasubiri jibu",
  "Server key for alerts (OUTBOX_SECRET)": "Ufunguo wa seva kwa tahadhari (OUTBOX_SECRET)",
  "Server setup for phone and email alerts →": "Usanidi wa seva kwa tahadhari za simu na barua pepe →",
  "Set credit limits on clients. Invoices above the limit need you to issue them.": "Weka viwango vya mkopo kwa wateja. Ankara zinazozidi kiwango zinahitaji uzitoe wewe.",
  "Set up your company": "Sanidi kampuni yako",
  "Setting up…": "Inasanidi…",
  "Settings": "Mipangilio",
  "Setup needed": "Usanidi unahitajika",
  "Share": "Shiriki",
  "Share PDF": "Shiriki PDF",
  "Share PDF prints the delivery note for the truck. After delivery it becomes the signed proof of delivery.": "Shiriki PDF huchapisha hati ya uwasilishaji kwa ajili ya lori. Baada ya uwasilishaji inakuwa uthibitisho wa uwasilishaji uliosainiwa.",
  "Share PDF sends the quotation by WhatsApp or email from your phone. Then press I have sent it to the client.": "Shiriki PDF hutuma nukuu ya bei kwa WhatsApp au barua pepe kutoka kwenye simu yako. Kisha bonyeza Nimeituma kwa mteja.",
  "Shelf life (months)": "Muda wa kukaa (miezi)",
  "Shipping instructions": "Maelekezo ya usafirishaji",
  "Short guide for your role, step by step": "Mwongozo mfupi wa jukumu lako, hatua kwa hatua",
  "Show": "Onyesha",
  "Show archived": "Onyesha zilizohifadhiwa kumbukumbu",
  "Show password": "Onyesha nenosiri",
  "Showing the first": "Inaonyesha za kwanza",
  "Sign in": "Ingia",
  "Sign in or create an account": "Ingia au fungua akaunti",
  "Sign out": "Toka",
  "Signature": "Sahihi",
  "Signed delivery note": "Hati ya uwasilishaji iliyosainiwa",
  "Signed-in users don't have access to the app's tables yet.": "Watumiaji walioingia bado hawana ruhusa ya kufikia majedwali ya programu.",
  "Signing out…": "Inatoka…",
  "Site visit": "Ziara ya eneo",
  "Something went wrong": "Kuna hitilafu imetokea",
  "Something wrong or missing? Tell management — every change is recorded in the activity log.": "Kuna kosa au kinakosekana? Waambie uongozi — kila badiliko linarekodiwa kwenye kumbukumbu ya shughuli.",
  "Specification": "Vipimo",
  "Spreadsheet (.xlsx)": "Lahajedwali (.xlsx)",
  "Standard PO terms": "Masharti ya kawaida ya PO",
  "Standard invoice terms": "Masharti ya kawaida ya ankara",
  "Standard quotation and PO terms": "Masharti ya kawaida ya nukuu ya bei na PO",
  "Standard terms and conditions": "Vigezo na masharti ya kawaida",
  "Start each day on Home": "Anza kila siku kwenye Mwanzo",
  "Status": "Hali",
  "Still owed on this list:": "Bado inadaiwa kwenye orodha hii:",
  "Still to pay": "Bado kulipa",
  "Stock": "Stoku",
  "Stock card": "Kadi ya stoku",
  "Stock movements": "Mienendo ya stoku",
  "Stock on hand, batches, expiry, adjustments": "Stoku iliyopo, bechi, kuisha muda, marekebisho",
  "Stock shows quantities per store and batch, expiring batches and items below reorder level. Adjust stock after counts (a reason is required).": "Stoku inaonyesha kiasi kwa kila ghala na bechi, bechi zinazokaribia kuisha muda na bidhaa zilizo chini ya kiwango cha kuagiza tena. Rekebisha stoku baada ya kuhesabu (sababu inahitajika).",
  "Store": "Ghala",
  "Stores": "Maghala",
  "Stores and warehouses": "Maghala na stoo",
  "Subcategory": "Kategoria ndogo",
  "Submit": "Wasilisha",
  "Submit purchase order": "Wasilisha oda ya ununuzi",
  "Submit quotation": "Wasilisha nukuu ya bei",
  "Submit sends it for approval when it is large, has a low margin or a big discount; otherwise it is approved straight away. You are told when management decides.": "Wasilisha huituma kwa idhini ikiwa ni kubwa, ina faida ndogo au punguzo kubwa; vinginevyo inaidhinishwa moja kwa moja. Utaarifiwa uongozi ukishaamua.",
  "Submitted by": "Imewasilishwa na",
  "Submitting…": "Inawasilisha…",
  "Subtotal": "Jumla ndogo",
  "Supabase Auth: Site URL and redirect URLs updated, Confirm email on, custom SMTP": "Supabase Auth: Site URL na redirect URLs zimesasishwa, Confirm email imewashwa, SMTP maalum",
  "Supplier": "Msambazaji",
  "Supplier ID": "ID ya msambazaji",
  "Supplier RFQ": "RFQ ya msambazaji",
  "Supplier RFQs": "RFQ za wasambazaji",
  "Supplier RFQs and purchase orders": "RFQ za wasambazaji na oda za ununuzi",
  "Supplier RFQs collecting prices": "RFQ za wasambazaji zinazokusanya bei",
  "Supplier bill": "Bili ya msambazaji",
  "Supplier bills": "Bili za wasambazaji",
  "Supplier confirmed": "Msambazaji amethibitisha",
  "Supplier name": "Jina la msambazaji",
  "Supplier prices": "Bei za wasambazaji",
  "Supplier's delivery note no.": "Namba ya hati ya uwasilishaji ya msambazaji",
  "Supplier's invoice no.": "Namba ya ankara ya msambazaji",
  "Supplier's invoices": "Ankara za msambazaji",
  "Supplier's quote reference": "Kumbukumbu ya bei ya msambazaji",
  "Suppliers": "Wasambazaji",
  "Suppliers asked (": "Wasambazaji walioulizwa (",
  "Suppliers should reply by": "Wasambazaji wajibu kabla ya",
  "Suppliers' invoices and payments": "Ankara za wasambazaji na malipo",
  "Switch": "Badilisha",
  "Switched off": "Imezimwa",
  "Switching…": "Inabadilisha…",
  "System": "Mfumo",
  "TIN / tax no.": "TIN / namba ya kodi",
  "TIN, VRN, address, phone and email filled in": "TIN, VRN, anwani, simu na barua pepe vimejazwa",
  "TT / transfer ref": "Kumbukumbu ya TT / uhamisho",
  "Tab not found in the file — skipped": "Kichupo hakikupatikana kwenye faili — kimerukwa",
  "Tax status": "Hali ya kodi",
  "Team": "Timu",
  "Team & roles": "Timu na majukumu",
  "Team (": "Timu (",
  "Team and roles": "Timu na majukumu",
  "Team invited with the right roles": "Timu imealikwa kwa majukumu sahihi",
  "Technical": "Kiufundi",
  "Tender": "Zabuni",
  "Terms": "Masharti",
  "Terms and conditions": "Vigezo na masharti",
  "Test transactions cleared": "Miamala ya majaribio imefutwa",
  "The amounts are filled in from the purchase order — change them to match the invoice.": "Kiasi kimejazwa kutoka kwenye oda ya ununuzi — kibadilishe kilingane na ankara.",
  "The app couldn't read your company from the database.": "Programu imeshindwa kusoma kampuni yako kutoka kwenye hifadhidata.",
  "The bell tells you when quotations are about to expire, when goods arrive and when the client pays.": "Kengele inakujulisha nukuu za bei zinapokaribia kuisha muda, bidhaa zinapofika na mteja anapolipa.",
  "The bell warns you when an expected delivery date passes, and when stock falls below the reorder level.": "Kengele inakuonya tarehe ya uwasilishaji inayotarajiwa inapopita, na stoku inaposhuka chini ya kiwango cha kuagiza tena.",
  "The client accepted. Ask suppliers for prices, or order directly.": "Mteja amekubali. Omba bei kwa wasambazaji, au agiza moja kwa moja.",
  "The control tower shows what is critical, what needs attention and what is in progress. Every line opens the list behind it.": "Mnara wa udhibiti unaonyesha yaliyo hatari, yanayohitaji uangalizi na yanayoendelea. Kila mstari unafungua orodha iliyo nyuma yake.",
  "The database isn't set up yet": "Hifadhidata bado haijasanidiwa",
  "The database refused the request": "Hifadhidata imekataa ombi",
  "The landed cost can be applied once the supplier has confirmed the order.": "Gharama halisi ya kufikisha inaweza kutumika msambazaji akishathibitisha oda.",
  "The page could not load. Check your internet connection and try again. If it keeps happening, send this reference to support:": "Ukurasa umeshindwa kufunguka. Angalia muunganisho wa intaneti na ujaribu tena. Ikiendelea kutokea, tuma kumbukumbu hii kwa msaada:",
  "The whole flow: client RFQ → quotation → approval → order won → supplier quotes → purchase order → goods received → delivery → proof of delivery → invoice → payment → profit. Each person does their part and the next person is told.": "Mtiririko mzima: RFQ ya mteja → nukuu ya bei → idhini → oda imepatikana → bei za wasambazaji → oda ya ununuzi → bidhaa zimepokelewa → uwasilishaji → uthibitisho wa uwasilishaji → ankara → malipo → faida. Kila mtu anafanya sehemu yake na anayefuata anaarifiwa.",
  "Their email": "Barua pepe yao",
  "Their offer": "Ofa yao",
  "Their order / confirmation no.": "Namba yao ya oda / uthibitisho",
  "Their quote reference": "Kumbukumbu ya nukuu yao",
  "Then in": "Kisha katika",
  "Then reload this app.": "Kisha pakia upya programu hii.",
  "These “Main supplier” names didn't match any supplier, so those products have no main supplier yet:": "Majina haya ya “Msambazaji mkuu” hayakulingana na msambazaji yeyote, kwa hiyo bidhaa hizo bado hazina msambazaji mkuu:",
  "This bill has payments, so it can no longer be changed.": "Bili hii ina malipo, kwa hiyo haiwezi kubadilishwa tena.",
  "This browser cannot receive notifications. Try Chrome on Android, or Safari on iPhone.": "Kivinjari hiki hakiwezi kupokea arifa. Jaribu Chrome kwenye Android, au Safari kwenye iPhone.",
  "This device": "Kifaa hiki",
  "Tip: to buy for a client order, open the accepted quotation (or the client RFQ) and use “Request supplier quotes” so the items are copied across.": "Kidokezo: kununua kwa ajili ya oda ya mteja, fungua nukuu ya bei iliyokubaliwa (au RFQ ya mteja) na utumie “Omba bei kwa wasambazaji” ili bidhaa zinakiliwe.",
  "Tips": "Vidokezo",
  "Title": "Kichwa",
  "To compare several suppliers first, use a": "Kulinganisha wasambazaji kadhaa kwanza, tumia",
  "To deliver": "Za kuwasilisha",
  "To deliver a won order, open the accepted quotation and use “Create delivery note”: the items are copied, and later deliveries only include what is still outstanding.": "Kuwasilisha oda iliyopatikana, fungua nukuu ya bei iliyokubaliwa na utumie “Tengeneza hati ya uwasilishaji”: bidhaa zinakiliwa, na uwasilishaji unaofuata unajumuisha kilichobaki tu.",
  "To do": "Za kufanya",
  "To invoice a whole order (for example an advance payment invoice), open the accepted quotation and use “Create invoice”.": "Kutoa ankara ya oda nzima (kwa mfano ankara ya malipo ya awali), fungua nukuu ya bei iliyokubaliwa na utumie “Tengeneza ankara”.",
  "To pay": "Za kulipa",
  "To pay within 7 days (or late)": "Za kulipa ndani ya siku 7 (au zilizochelewa)",
  "Total": "Jumla",
  "Total (": "Jumla (",
  "Total (excl. VAT)": "Jumla (bila VAT)",
  "Total extra costs": "Jumla ya gharama za ziada",
  "Total landed": "Jumla ya gharama hadi ghalani",
  "Total outstanding": "Jumla inayodaiwa",
  "Trading name": "Jina la biashara",
  "Try again": "Jaribu tena",
  "Turn off": "Zima",
  "Turn on notifications on this device": "Washa arifa kwenye kifaa hiki",
  "Turn on phone notifications under Notifications → This device.": "Washa arifa za simu kupitia Arifa → Kifaa hiki.",
  "Turning on…": "Inawasha…",
  "Type": "Aina",
  "Type it again": "Iandike tena",
  "Type the prices exactly as the supplier quoted them, in their currency. Leave an item empty if they can't supply it.": "Andika bei kama msambazaji alivyozinukuu, kwa sarafu yao. Acha bidhaa wazi kama hawawezi kuisambaza.",
  "UN no.": "Namba ya UN",
  "Undo declined": "Tendua kukataliwa",
  "Unit": "Kipimo",
  "Unit price": "Bei kwa kipimo",
  "Unit prices": "Bei kwa kipimo",
  "Unit prices converted to": "Bei kwa kipimo zimebadilishwa kuwa",
  "Unpaid": "Haijalipwa",
  "Unpaid invoices by client and how late they are. Foreign-currency invoices are shown in": "Ankara zisizolipwa kwa kila mteja na zimechelewa kiasi gani. Ankara za fedha za kigeni zinaonyeshwa kwa",
  "Unpaid supplier bills. Totals are converted to": "Bili za wasambazaji zisizolipwa. Jumla zimebadilishwa kuwa",
  "Update": "Sasisha",
  "Update rates when the bank rate moves.": "Sasisha viwango benki inapobadilisha kiwango.",
  "Updated": "Imesasishwa",
  "Updates each product's cost, so quotation margins and profit use the real cost.": "Inasasisha gharama ya kila bidhaa, ili faida za nukuu za bei zitumie gharama halisi.",
  "Upload logo": "Pakia nembo",
  "Upload your logo and set your colours": "Pakia nembo yako na uweke rangi zako",
  "Urgent": "Haraka",
  "Use landed cost as product cost": "Tumia gharama hadi ghalani kama gharama ya bidhaa",
  "Use this for opening balances when you start, after a stock count, or to write off damaged or expired goods. Every adjustment is recorded with your name and reason.": "Tumia hii kwa salio la mwanzo unapoanza, baada ya kuhesabu stoku, au kufuta bidhaa zilizoharibika au zilizokwisha muda. Kila marekebisho yanarekodiwa pamoja na jina lako na sababu.",
  "Use this once at go-live to record what is physically in your stores. Count first, then fill in the template: one row per product, store and batch. If any row has a problem, nothing is loaded and you are told which rows to fix. Each row is recorded as an “Opening stock” adjustment.": "Tumia hii mara moja wakati wa kuanza kurekodi kilichopo kwenye maghala yako. Hesabu kwanza, kisha jaza kiolezo: mstari mmoja kwa kila bidhaa, ghala na bechi. Mstari wowote ukiwa na tatizo, hakuna kinachopakiwa na unaambiwa mistari ipi urekebishe. Kila mstari unarekodiwa kama marekebisho ya “Stoku ya mwanzo”.",
  "Used in the app and on your documents.": "Inatumika kwenye programu na kwenye nyaraka zako.",
  "Usually you invoice each delivery from its delivery note. Use this for advance or whole-order invoices.": "Kwa kawaida unatoa ankara kwa kila uwasilishaji kutoka kwenye hati yake ya uwasilishaji. Tumia hii kwa ankara za malipo ya awali au za oda nzima.",
  "VAT %": "VAT %",
  "VAT amount": "Kiasi cha VAT",
  "VAT rate %": "Kiwango cha VAT %",
  "Valid until": "Halali hadi",
  "Vehicle": "Gari",
  "Versions": "Matoleo",
  "View the company's details": "Angalia taarifa za kampuni",
  "Void": "Batilisha",
  "Void this payment": "Batilisha malipo haya",
  "Voided:": "Imebatilishwa:",
  "Waiting for approval": "Inasubiri idhini",
  "Waiting for management approval": "Inasubiri idhini ya menejimenti",
  "Waiting for price": "Inasubiri bei",
  "Waiting for your approval": "Inasubiri idhini yako",
  "Waiting to join": "Inasubiri kujiunga",
  "Warehouses and store locations": "Maghala na maeneo ya kuhifadhi",
  "Warranty (months)": "Dhamana (miezi)",
  "We owe suppliers": "Tunadaiwa na wasambazaji",
  "Website": "Tovuti",
  "Welcome": "Karibu",
  "Welcome back": "Karibu tena",
  "What arrived": "Kilichofika",
  "What can each role do?": "Kila jukumu linaweza kufanya nini?",
  "What is ready and what is left": "Kilicho tayari na kilichobaki",
  "What is ready and what is left before everyone starts": "Kilicho tayari na kilichobaki kabla kila mtu hajaanza",
  "What they asked for": "Walichoomba",
  "What they supply": "Wanachosambaza",
  "What you need": "Unachohitaji",
  "When": "Lini",
  "When a client asks for prices (email, phone, WhatsApp, visit), create a client RFQ with the items and due date. You get a reminder when it is due.": "Mteja anapoomba bei (barua pepe, simu, WhatsApp, ziara), tengeneza RFQ ya mteja yenye bidhaa na tarehe ya mwisho. Utapata kikumbusho ikifika.",
  "When the client replies, press Client accepted (add their PO number) or Client declined. Accepted orders go to procurement automatically.": "Mteja akijibu, bonyeza Mteja amekubali (ongeza namba yao ya PO) au Mteja amekataa. Oda zilizokubaliwa zinaenda kwa ununuzi moja kwa moja.",
  "When you submit, the app checks the margin and value. If they're within the rules it's approved straight away; otherwise management is asked to approve.": "Ukiwasilisha, programu inakagua faida na thamani. Zikiwa ndani ya kanuni inaidhinishwa papo hapo; vinginevyo menejimenti inaombwa kuidhinisha.",
  "Where": "Wapi",
  "Whole-order profit, including freight and other costs →": "Faida ya oda nzima, ikijumuisha usafirishaji na gharama nyingine →",
  "Won": "Imepatikana",
  "Won orders": "Oda zilizopatikana",
  "Won orders to buy for": "Oda zilizopatikana za kununulia",
  "Working…": "Inafanya kazi…",
  "Yes": "Ndiyo",
  "You": "Wewe",
  "You are told when a delivery is completed. Open it and press Create invoice, check it, then Issue invoice and share the PDF.": "Unaarifiwa uwasilishaji unapokamilika. Ufungue na ubonyeze Tengeneza ankara, ikague, kisha Toa ankara na ushiriki PDF.",
  "You are told when an order is won. Open it and press Request supplier quotes, or Create purchase order if you already know the supplier.": "Unaarifiwa oda inapopatikana. Ifungue na ubonyeze Omba bei kwa wasambazaji, au Tengeneza oda ya ununuzi kama tayari unamjua msambazaji.",
  "You buy the goods at the best price and make sure they arrive on time.": "Unanunua bidhaa kwa bei nzuri zaidi na kuhakikisha zinafika kwa wakati.",
  "You can": "Unaweza",
  "You can add the supplier and cost after saving.": "Unaweza kuongeza msambazaji na gharama baada ya kuhifadhi.",
  "You can ask suppliers for prices already.": "Unaweza tayari kuomba bei kwa wasambazaji.",
  "You deliver the goods and record proof of delivery on your phone.": "Unawasilisha bidhaa na kurekodi uthibitisho wa uwasilishaji kwenye simu yako.",
  "You invoice, collect money, pay suppliers and watch profit.": "Unatoa ankara, unakusanya fedha, unalipa wasambazaji na kufuatilia faida.",
  "You receive goods, keep stock right, and send deliveries out.": "Unapokea bidhaa, unaweka stoku sahihi, na unatuma uwasilishaji.",
  "You see everything, approve, and keep the system set up.": "Unaona kila kitu, unaidhinisha, na unasimamia mipangilio ya mfumo.",
  "You signed in successfully, but the app's tables aren't in the database yet. An administrator needs to run the setup file once in Supabase:": "Umeingia kwa mafanikio, lakini majedwali ya programu bado hayapo kwenye hifadhidata. Msimamizi anahitaji kuendesha faili la usanidi mara moja kwenye Supabase:",
  "You turn client requests into won orders.": "Unageuza maombi ya wateja kuwa oda zilizopatikana.",
  "You'll be its first manager and can invite your team afterwards. If your company already uses this app, ask a manager to invite": "Utakuwa meneja wake wa kwanza na unaweza kualika timu yako baadaye. Kama kampuni yako tayari inatumia programu hii, muombe meneja akualike",
  "You're signed in. Choose a new password below.": "Umeingia. Chagua nenosiri jipya hapa chini.",
  "You've been invited": "Umealikwa",
  "Your account": "Akaunti yako",
  "Your alerts, phone notifications and emails": "Tahadhari zako, arifa za simu na barua pepe",
  "Your companies": "Kampuni zako",
  "Your data": "Data yako",
  "Your data belongs to you. Download it any time, as a backup or to move to other software. CSV files open in Excel. The JSON file contains everything in one file. Signatures, photos and logos are not included (they stay in file storage).": "Data yako ni mali yako. Ipakue wakati wowote, kama nakala ya akiba au kuihamishia programu nyingine. Faili za CSV zinafunguka kwenye Excel. Faili la JSON lina kila kitu katika faili moja. Saini, picha na nembo hazijumuishwi (zinabaki kwenye hifadhi ya faili).",
  "Your decision": "Uamuzi wako",
  "Your details": "Taarifa zako",
  "Your details, password, sign out": "Taarifa zako, nenosiri, toka",
  "Your notifications": "Arifa zako",
  "Your own web address": "Anwani yako ya wavuti",
  "Your role:": "Jukumu lako:",
  "a LeMo Tech Solutions product": "bidhaa ya LeMo Tech Solutions",
  "active)": "hai)",
  "added": "imeongezwa",
  "added ·": "imeongezwa ·",
  "and": "na",
  "and award the winner: the PO is created for you.": "na umchague mshindi: PO inatengenezwa kwa ajili yako.",
  "appears at the bottom of quotations and invoices": "inaonekana chini ya nukuu za bei na ankara",
  "as": "kama",
  "as on BRELA certificate": "kama ilivyo kwenye cheti cha BRELA",
  "at each bill's rate.": "kwa kiwango cha kila bili.",
  "at the rate on this quotation (": "kwa kiwango kilicho kwenye nukuu hii ya bei (",
  "at their invoice rate.": "kwa kiwango cha ankara yao.",
  "automatic checks done. Items marked • can't be checked from inside the app — follow the go-live runbook (GO-LIVE.md in the project) for those.": "ukaguzi wa kiotomatiki umefanyika. Vipengele vilivyowekwa alama • haviwezi kukaguliwa ndani ya programu — fuata mwongozo wa kuanza (GO-LIVE.md kwenye mradi) kwa hivyo.",
  "bank, branch, account name and numbers, SWIFT": "benki, tawi, jina la akaunti na namba, SWIFT",
  "because:": "kwa sababu:",
  "below this needs approval": "chini ya hii inahitaji idhini",
  "by": "na",
  "contents": "yaliyomo",
  "days": "siku",
  "days after": "siku baada ya",
  "days overdue": "siku imechelewa",
  "despite:": "licha ya:",
  "done": "imekamilika",
  "draft": "rasimu",
  "draft invoice": "rasimu ya ankara",
  "due": "tarehe ya mwisho",
  "e.g. 2 cartons wet": "mf. 2 cartons wet",
  "e.g. 20 drums hydraulic oil": "mf. 20 drums hydraulic oil",
  "e.g. 2–3 weeks after PO": "mf. wiki 2–3 baada ya PO",
  "e.g. Dar es Salaam store": "mf. ghala la Dar es Salaam",
  "e.g. GTA": "mf. GTA",
  "e.g. Geita store": "mf. ghala la Geita",
  "e.g. OK for this client; or: reduce discount to 5%": "mf. Sawa kwa mteja huyu; au: punguza punguzo hadi 5%",
  "e.g. Opening balance / count 30 Sep / damaged": "mf. Salio la mwanzo / hesabu 30 Sep / imeharibika",
  "e.g. Stock of hydraulic oil for Q4": "mf. Stoku ya hydraulic oil kwa Q4",
  "e.g. T 123 ABC": "mf. T 123 ABC",
  "e.g. TRA duty, agent invoice no.": "mf. ushuru wa TRA, namba ya ankara ya wakala",
  "e.g. TRIUMPH General Suppliers Ltd": "mf. TRIUMPH General Suppliers Ltd",
  "e.g. client wants SKF only": "mf. mteja anataka SKF tu",
  "e.g. offers FAG instead of SKF; price excludes CoA": "mf. anatoa FAG badala ya SKF; bei haijumuishi CoA",
  "e.g. site closed, client refused": "mf. eneo limefungwa, mteja amekataa",
  "expired": "imekwisha muda",
  "expires": "inaisha",
  "falls due in the next 7 days.": "inafika tarehe ya mwisho ndani ya siku 7 zijazo.",
  "for 1 unit of each currency. Quotations, purchase orders, invoices, bills and costs in a foreign currency take this rate automatically, and can only differ from it by up to 10%. This keeps approval limits, credit limits and margins honest.": "kwa kipimo 1 cha kila sarafu. Nukuu za bei, oda za ununuzi, ankara, bili na gharama kwa fedha za kigeni zinachukua kiwango hiki moja kwa moja, na zinaweza kutofautiana nacho kwa hadi 10% tu. Hii inaweka mipaka ya idhini, mipaka ya mkopo na faida kuwa za kweli.",
  "for POs raised by procurement": "kwa PO zinazotolewa na ununuzi",
  "found": "zimepatikana",
  "if VAT registered": "kama umesajiliwa kwa VAT",
  "import them from your spreadsheet": "ziingize kutoka kwenye lahajedwali yako",
  "in progress": "inaendelea",
  "in stock": "ipo stoku",
  "in the spreadsheet, then choose the file again:": "kwenye lahajedwali, kisha chagua faili tena:",
  "incl. VAT": "pamoja na VAT",
  "instead.": "badala yake.",
  "into": "kwenda",
  "invoice": "ankara",
  "invoiced line": "mstari wenye ankara",
  "items": "bidhaa",
  "late, was due": "imechelewa, ilitakiwa",
  "leave blank to number automatically": "acha wazi ili kuweka namba kiotomatiki",
  "manage": "simamia",
  "management or finance only": "menejimenti au fedha tu",
  "more": "zaidi",
  "more.": "zaidi.",
  "need management approval (unless you are management).": "zinahitaji idhini ya menejimenti (isipokuwa wewe ni menejimenti).",
  "never": "kamwe",
  "next": "ijayo",
  "no product cost, so profit is overstated. Set costs on the products (or confirm their purchase orders) before invoicing.": "hakuna gharama ya bidhaa, kwa hiyo faida imezidishwa. Weka gharama kwenye bidhaa (au thibitisha oda zao za ununuzi) kabla ya kutoa ankara.",
  "no reference": "hakuna kumbukumbu",
  "not a catalogue item": "si bidhaa ya katalogi",
  "not quoted": "haijanukuliwa",
  "of": "ya",
  "of opening stock.": "ya stoku ya mwanzo.",
  "of which VAT": "ambapo VAT",
  "on": "tarehe",
  "on their phone and taps": "kwenye simu yake na kubonyeza",
  "per": "kwa",
  "per 1": "kwa 1",
  "per 1 unit": "kwa kipimo 1",
  "per 1 unit (ignored for": "kwa kipimo 1 (inapuuzwa kwa",
  "price / unit": "bei / kipimo",
  "priced": "imewekewa bei",
  "printed on every invoice": "inachapishwa kwenye kila ankara",
  "printed on every purchase order": "inachapishwa kwenye kila oda ya ununuzi",
  "printed on every quotation": "inachapishwa kwenye kila nukuu ya bei",
  "problem": "tatizo",
  "quotations need a manager before they can be sent.": "nukuu za bei zinahitaji meneja kabla hazijatumwa.",
  "ready,": "tayari,",
  "row": "mstari",
  "sets the due date when an invoice is issued": "inaweka tarehe ya mwisho ankara inapotolewa",
  "supplier": "msambazaji",
  "supplier RFQ": "RFQ ya msambazaji",
  "to do": "ya kufanya",
  "units in total.": "vipimo kwa jumla.",
  "updated": "imesasishwa",
  "view supplier": "angalia msambazaji",
  "with exactly the same text, and redeploy. This lets the server send alerts without any database password.": "yenye maandishi yaleyale kabisa, na usambaze upya. Hii inaruhusu seva kutuma tahadhari bila nenosiri lolote la hifadhidata.",
  "· 0 for foreign suppliers": "· 0 kwa wasambazaji wa nje",
  "· added": "· imeongezwa",
  "· already received": "· tayari imepokelewa",
  "· at least 8 characters": "· angalau herufi 8",
  "· batch": "· bechi",
  "· blank =": "· wazi =",
  "· blank = the day it is issued": "· wazi = siku inayotolewa",
  "· by": "· na",
  "· damaged, not in stock": "· imeharibika, haipo stoku",
  "· dated": "· ya tarehe",
  "· deliver to": "· wasilisha kwa",
  "· driver": "· dereva",
  "· due": "· tarehe ya mwisho",
  "· e.g. 2600 for USD": "· mf. 2600 kwa USD",
  "· e.g. PO number, or why they declined": "· mf. namba ya PO, au kwa nini wamekataa",
  "· empty = catalogue price": "· wazi = bei ya katalogi",
  "· expired": "· imekwisha muda",
  "· expires": "· inaisha",
  "· filled from the product if left empty": "· inajazwa kutoka kwenye bidhaa ikiachwa wazi",
  "· from": "· kutoka",
  "· if not": "· kama sivyo",
  "· if the product has batches": "· kama bidhaa ina bechi",
  "· invited": "· amealikwa",
  "· issued": "· imetolewa",
  "· or leave empty and describe it below": "· au acha wazi na uieleze hapa chini",
  "· planned": "· imepangwa",
  "· printed on the invoice": "· inachapishwa kwenye ankara",
  "· printed on the quotation": "· inachapishwa kwenye nukuu ya bei",
  "· received": "· imepokelewa",
  "· reorder at": "· agiza tena kwa",
  "· reply by": "· jibu kabla ya",
  "· required": "· inahitajika",
  "· required when sending back": "· inahitajika unaporudisha",
  "· short summary": "· muhtasari mfupi",
  "· their DN": "· DN yao",
  "· their RFQ / PR no.": "· namba yao ya RFQ / PR",
  "· their invoice": "· ankara yao",
  "· their ref": "· kumbukumbu yao",
  "· to come": "· zinazokuja",
  "· valid until": "· halali hadi",
  "· validity expired": "· muda wa uhalali umekwisha",
  "– the key": "– ufunguo",
  "— Not in the catalogue —": "— Haipo kwenye katalogi —",
  "— profit is overstated": "— faida imezidishwa",
  "…and": "…na",
  "← Clients": "← Wateja",
  "← Deliveries": "← Uwasilishaji",
  "← Earlier": "← Awali",
  "← Finance": "← Fedha",
  "← Invoices": "← Ankara",
  "← Products": "← Bidhaa",
  "← Purchase orders": "← Oda za ununuzi",
  "← Purchasing": "← Ununuzi",
  "← Quotations": "← Nukuu za bei",
  "← RFQs": "← RFQ",
  "← Receive goods": "← Pokea bidhaa",
  "← Sales": "← Mauzo",
  "← Settings": "← Mipangilio",
  "← Stock": "← Stoku",
  "← Supplier RFQs": "← RFQ za wasambazaji",
  "← Supplier bills": "← Bili za wasambazaji",
  "← Suppliers": "← Wasambazaji",
  "≈ in": "≈ kwa",
};
